In [129]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.legend import Legend
import matplotlib.patches as mpatches
import seaborn as sns
#from statsmodels.graphics.mosaicplot import mosaic
import io
import requests

## Lectura de los archivos de test y train

In [130]:
url_test="https://raw.githubusercontent.com/joacols/TP_orga_de_datos/main/Test_TP2_Datos_2020-2C.csv"
s_test=requests.get(url_test).content
df_test=pd.read_csv(io.StringIO(s_test.decode('utf-8')),

#df = pd.read_csv('Entrenamieto_ECI_2020.csv',
dtype={
'ID': np.int64,
'Pricing, Delivery_Terms_Quote_Approval': np.int64,
'Pricing, Delivery_Terms_Approved': np.int64,
'Bureaucratic_Code_0_Approval': np.int64,
'Bureaucratic_Code_0_Approved': np.int64,
'Submitted_for_Approval': np.int64,
'Opportunity_ID': np.int64,
#'Sales_Contract_No': np.int64,
'Delivery_Year': np.int64,
'Total_Power': np.int64,
#'Price':np.float64,
'ASP':np.float64,
'ASP_(converted)':np.float64,
'Total_Amount':np.float64},
parse_dates=[
'Account_Created_Date',
'Planned_Delivery_Start_Date',
'Planned_Delivery_End_Date',
'Opportunity_Created_Date',
'Last_Activity',
'Quote_Expiry_Date',
'Actual_Delivery_Date',
'Last_Modified_Date'
])

df_test

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Month,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Prod_Category_A
0,6140,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 5,Q2,2019,NaT,0,EUR,162240.0,EUR,367419.0,Prod_Category_A_None
1,6146,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 5,Q2,2019,NaT,0,EUR,78624.0,EUR,367419.0,Prod_Category_A_None
2,6151,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 5,Q2,2019,NaT,0,EUR,126555.0,EUR,367419.0,Prod_Category_A_None
3,6118,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 6,Q2,2019,NaT,1,EUR,243360.0,EUR,757783.5,Prod_Category_A_None
4,6124,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 6,Q2,2019,NaT,0,EUR,157248.0,EUR,757783.5,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2546,16345,EMEA,KSA,1,1,0,0,0,Bureaucratic_Code_4,2017-06-12,...,2019 - 5,Q2,2019,NaT,0,USD,124740.0,USD,147750.0,Prod_Category_A_None
2547,15218,Americas,SE America,1,1,0,0,0,Bureaucratic_Code_4,2018-06-08,...,2019 - 10,Q4,2019,NaT,0,USD,45054.9,USD,45054.9,Prod_Category_A_None
2548,15224,Americas,SE America,1,1,1,1,0,Bureaucratic_Code_4,2018-06-08,...,2019 - 10,Q4,2019,NaT,0,USD,100122.0,USD,100122.0,Prod_Category_A_None
2549,7286,Americas,NE America,1,1,0,0,0,Bureaucratic_Code_4,2018-08-29,...,2019 - 8,Q3,2019,NaT,0,USD,143220.0,USD,143220.0,Prod_Category_A_None
2550,11263,EMEA,Belgium,1,0,0,0,0,Bureaucratic_Code_5,2016-03-03,...,2019 - 10,Q4,2019,NaT,3,EUR,871020.8,EUR,871020.8,Prod_Category_A_None

In [131]:
url_train="https://raw.githubusercontent.com/joacols/TP_orga_de_datos/main/Train_TP2_Datos_2020-2C.csv"
s_train=requests.get(url_train).content
df_train=pd.read_csv(io.StringIO(s_train.decode('utf-8')),

#df = pd.read_csv('Entrenamieto_ECI_2020.csv',
dtype={
'ID': np.int64,
'Pricing, Delivery_Terms_Quote_Approval': np.int64,
'Pricing, Delivery_Terms_Approved': np.int64,
'Bureaucratic_Code_0_Approval': np.int64,
'Bureaucratic_Code_0_Approved': np.int64,
'Submitted_for_Approval': np.int64,
'Opportunity_ID': np.int64,
#'Sales_Contract_No': np.int64,
'Delivery_Year': np.int64,
'Total_Power': np.int64,
#'Price':np.float64,
'ASP':np.float64,
'ASP_(converted)':np.float64,
'Total_Amount':np.float64},
parse_dates=[
'Account_Created_Date',
'Planned_Delivery_Start_Date',
'Planned_Delivery_End_Date',
'Opportunity_Created_Date',
'Last_Activity',
'Quote_Expiry_Date',
'Actual_Delivery_Date',
'Last_Modified_Date'
])

df_train

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,Q2,2016,NaT,10,EUR,5272800.00,EUR,5272800.0,Closed Lost,Prod_Category_A_None
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,Q1,2016,NaT,0,EUR,48230.00,EUR,48230.0,Closed Won,Prod_Category_A_None
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,Q1,2016,NaT,0,USD,83865.60,USD,83865.6,Closed Won,Prod_Category_A_None
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,14,USD,7421881.50,USD,7421881.5,Closed Lost,Prod_Category_A_None
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,25,USD,13357192.50,USD,13357192.5,Closed Lost,Prod_Category_A_None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16942,8781,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q1,2016,NaT,0,EUR,103350.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16943,8786,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q2,2016,NaT,0,EUR,93015.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16944,8792,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,Q1,2016,NaT,0,EUR,103350.00,EUR,299715.0,Closed Won,Prod_Category_A_None
16945,28561,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-10-20,...,Q2,2016,NaT,4,USD,2346796.88,USD,0.0,Closed Lost,Prod_Category_A_None
16946,28318,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-09-03,...,Q3,2016,NaT,40,USD,25603200.00,USD,0.0,Closed Lost,Prod_Category_A_None

## Chequeo de caracteristicas de los set de datos

### Chequeo de dimensiones del set de datos

In [132]:
df_test.shape

(2551, 51)

In [133]:
df_train.shape

(16947, 52)

In [134]:
df_test['Opportunity_ID'].value_counts()

12266    26
10973    24
11089    18
11869    15
11248    11
         ..
11778     1
12181     1
12179     1
11518     1
11488     1
Name: Opportunity_ID, Length: 1567, dtype: int64

In [135]:
df_train['Opportunity_ID'].value_counts()

12460    36
2008     36
5123     26
6606     26
2911     24
         ..
7482      1
5435      1
3400      1
7498      1
0         1
Name: Opportunity_ID, Length: 9841, dtype: int64

In [136]:
#df_test.describe()

## Creacion de nuevas columnas a partir de columnas que contienen fechas

In [137]:
df_train.select_dtypes(include=['datetime']).head()

,Account_Created_Date,Opportunity_Created_Date,Last_Activity,Quote_Expiry_Date,Last_Modified_Date,Planned_Delivery_Start_Date,Planned_Delivery_End_Date,Actual_Delivery_Date
0,2015-06-16,2015-12-07,NaT,2016-01-30,2016-06-13,2016-05-01,2016-06-30,NaT
1,2015-06-16,2015-12-07,NaT,2016-01-20,2016-01-15,2016-01-18,2016-01-20,NaT
2,2015-04-21,2015-12-08,NaT,2016-09-30,2016-09-29,2016-01-25,2016-01-25,NaT
3,2013-07-27,2015-12-08,NaT,NaT,2018-03-27,2018-02-01,2018-03-31,NaT
4,2013-07-27,2015-12-08,NaT,2017-06-02,2018-03-27,2018-02-01,2018-02-28,NaT

In [138]:
df_train['Account_Created_Date_Day'] = df_train['Account_Created_Date'].dt.day
df_train['Account_Created_Date_Month'] = df_train['Account_Created_Date'].dt.month
df_train['Account_Created_Date_Year'] = df_train['Account_Created_Date'].dt.year

df_train['Opportunity_Created_Date_Day'] = df_train['Opportunity_Created_Date'].dt.day
df_train['Opportunity_Created_Date_Month'] = df_train['Opportunity_Created_Date'].dt.month
df_train['Opportunity_Created_Date_Year'] = df_train['Opportunity_Created_Date'].dt.year

df_train['Last_Activity_Day'] = df_train['Last_Activity'].dt.day
df_train['Last_Activity_Month'] = df_train['Last_Activity'].dt.month
df_train['Last_Activity_Year'] = df_train['Last_Activity'].dt.year

df_train['Quote_Expiry_Date_Day'] = df_train['Quote_Expiry_Date'].dt.day
df_train['Quote_Expiry_Date_Month'] = df_train['Quote_Expiry_Date'].dt.month
df_train['Quote_Expiry_Date_Year'] = df_train['Quote_Expiry_Date'].dt.year

df_train['Last_Modified_Date_Day'] = df_train['Last_Modified_Date'].dt.day
df_train['Last_Modified_Date_Month'] = df_train['Last_Modified_Date'].dt.month
df_train['Last_Modified_Date_Year'] = df_train['Last_Modified_Date'].dt.year

df_train['Planned_Delivery_Start_Date_Day'] = df_train['Planned_Delivery_Start_Date'].dt.day
df_train['Planned_Delivery_Start_Date_Month'] = df_train['Planned_Delivery_Start_Date'].dt.month
df_train['Planned_Delivery_Start_Date_Year'] = df_train['Planned_Delivery_Start_Date'].dt.year

df_train['Planned_Delivery_End_Date_Day'] = df_train['Planned_Delivery_End_Date'].dt.day
df_train['Planned_Delivery_End_Date_Month'] = df_train['Planned_Delivery_End_Date'].dt.month
df_train['Planned_Delivery_End_Date_Year'] = df_train['Planned_Delivery_End_Date'].dt.year

df_train['Actual_Delivery_Date_Day'] = df_train['Actual_Delivery_Date'].dt.day
df_train['Actual_Delivery_Date_Month'] = df_train['Actual_Delivery_Date'].dt.month
df_train['Actual_Delivery_Date_Year'] = df_train['Actual_Delivery_Date'].dt.year

###
df_test['Account_Created_Date_Day'] = df_test['Account_Created_Date'].dt.day
df_test['Account_Created_Date_Month'] = df_test['Account_Created_Date'].dt.month
df_test['Account_Created_Date_Year'] = df_test['Account_Created_Date'].dt.year

df_test['Opportunity_Created_Date_Day'] = df_test['Opportunity_Created_Date'].dt.day
df_test['Opportunity_Created_Date_Month'] = df_test['Opportunity_Created_Date'].dt.month
df_test['Opportunity_Created_Date_Year'] = df_test['Opportunity_Created_Date'].dt.year

df_test['Last_Activity_Day'] = df_test['Last_Activity'].dt.day
df_test['Last_Activity_Month'] = df_test['Last_Activity'].dt.month
df_test['Last_Activity_Year'] = df_test['Last_Activity'].dt.year

df_test['Quote_Expiry_Date_Day'] = df_test['Quote_Expiry_Date'].dt.day
df_test['Quote_Expiry_Date_Month'] = df_test['Quote_Expiry_Date'].dt.month
df_test['Quote_Expiry_Date_Year'] = df_test['Quote_Expiry_Date'].dt.year

df_test['Last_Modified_Date_Day'] = df_test['Last_Modified_Date'].dt.day
df_test['Last_Modified_Date_Month'] = df_test['Last_Modified_Date'].dt.month
df_test['Last_Modified_Date_Year'] = df_test['Last_Modified_Date'].dt.year

df_test['Planned_Delivery_Start_Date_Day'] = df_test['Planned_Delivery_Start_Date'].dt.day
df_test['Planned_Delivery_Start_Date_Month'] = df_test['Planned_Delivery_Start_Date'].dt.month
df_test['Planned_Delivery_Start_Date_Year'] = df_test['Planned_Delivery_Start_Date'].dt.year

df_test['Planned_Delivery_End_Date_Day'] = df_test['Planned_Delivery_End_Date'].dt.day
df_test['Planned_Delivery_End_Date_Month'] = df_test['Planned_Delivery_End_Date'].dt.month
df_test['Planned_Delivery_End_Date_Year'] = df_test['Planned_Delivery_End_Date'].dt.year

df_test['Actual_Delivery_Date_Day'] = df_test['Actual_Delivery_Date'].dt.day
df_test['Actual_Delivery_Date_Month'] = df_test['Actual_Delivery_Date'].dt.month
df_test['Actual_Delivery_Date_Year'] = df_test['Actual_Delivery_Date'].dt.year

In [139]:
df_train[['Month','Delivery_Year']].head()

      Month  Delivery_Year
0  2016 - 5           2016
1  2016 - 1           2016
2  2016 - 1           2016
3  2018 - 2           2018
4  2018 - 2           2018

In [140]:
df_train["Delivery_Month"] = df_train['Month'].map(lambda x: x.split('-')[1])
df_train = df_train.astype({"Delivery_Month": np.int8})

df_train["Delivery_Month"].head()

0    5
1    1
2    1
3    2
4    2
Name: Delivery_Month, dtype: int8

In [141]:
df_test["Delivery_Month"] = df_test['Month'].map(lambda x: x.split('-')[1])
df_test = df_test.astype({"Delivery_Month": np.int8})

df_test["Delivery_Month"].head()

0    5
1    5
2    5
3    6
4    6
Name: Delivery_Month, dtype: int8

Delivery_Quarter es la columna que describe el cuatrimestre de entrega. En lugar de que sea texto solo dejaré el numero de cuatrimestre( esto resultará útil para los modelos que solo trabajen con datos numéricos)

In [142]:
df_train['Delivery_Quarter'].value_counts()

Q2    4443
Q1    4317
Q4    4144
Q3    4043
Name: Delivery_Quarter, dtype: int64

In [143]:
df_train['Delivery_Quarter']=df_train['Delivery_Quarter'].str.slice(start=-1).astype(float)
df_train['Delivery_Quarter'].value_counts()

2.0    4443
1.0    4317
4.0    4144
3.0    4043
Name: Delivery_Quarter, dtype: int64

In [144]:
df_test['Delivery_Quarter']=df_test['Delivery_Quarter'].str.slice(start=-1).astype(float)

## Uniendo los 2 dataframes

In [145]:
vertical_stack = pd.concat([df_train, df_test], axis=0)
vertical_stack

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Planned_Delivery_Start_Date_Day,Planned_Delivery_Start_Date_Month,Planned_Delivery_Start_Date_Year,Planned_Delivery_End_Date_Day,Planned_Delivery_End_Date_Month,Planned_Delivery_End_Date_Year,Actual_Delivery_Date_Day,Actual_Delivery_Date_Month,Actual_Delivery_Date_Year,Delivery_Month
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,1,5,2016,30.0,6.0,2016.0,NaN,NaN,NaN,5
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,18,1,2016,20.0,1.0,2016.0,NaN,NaN,NaN,1
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,25,1,2016,25.0,1.0,2016.0,NaN,NaN,NaN,1
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,1,2,2018,31.0,3.0,2018.0,NaN,NaN,NaN,2
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,1,2,2018,28.0,2.0,2018.0,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2546,16345,EMEA,KSA,1,1,0,0,0,Bureaucratic_Code_4,2017-06-12,...,1,5,2019,10.0,5.0,2019.0,NaN,NaN,NaN,5
2547,15218,Americas,SE America,1,1,0,0,0,Bureaucratic_Code_4,2018-06-08,...,1,10,2019,31.0,12.0,2019.0,NaN,NaN,NaN,10
2548,15224,Americas,SE America,1,1,1,1,0,Bureaucratic_Code_4,2018-06-08,...,1,10,2019,31.0,12.0,2019.0,NaN,NaN,NaN,10
2549,7286,Americas,NE America,1,1,0,0,0,Bureaucratic_Code_4,2018-08-29,...,1,8,2019,1.0,8.0,2019.0,NaN,NaN,NaN,8
2550,11263,EMEA,Belgium,1,0,0,0,0,Bureaucratic_Code_5,2016-03-03,...,21,10,2019,13.0,12.0,2019.0,NaN,NaN,NaN,10

In [146]:
df_1 = vertical_stack.iloc[:16947,:] 
df_2 = vertical_stack.iloc[16947:,:]

In [147]:
df_1

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Planned_Delivery_Start_Date_Day,Planned_Delivery_Start_Date_Month,Planned_Delivery_Start_Date_Year,Planned_Delivery_End_Date_Day,Planned_Delivery_End_Date_Month,Planned_Delivery_End_Date_Year,Actual_Delivery_Date_Day,Actual_Delivery_Date_Month,Actual_Delivery_Date_Year,Delivery_Month
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,1,5,2016,30.0,6.0,2016.0,NaN,NaN,NaN,5
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,18,1,2016,20.0,1.0,2016.0,NaN,NaN,NaN,1
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,25,1,2016,25.0,1.0,2016.0,NaN,NaN,NaN,1
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,1,2,2018,31.0,3.0,2018.0,NaN,NaN,NaN,2
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,1,2,2018,28.0,2.0,2018.0,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16942,8781,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,21,3,2016,25.0,3.0,2016.0,NaN,NaN,NaN,3
16943,8786,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,4,4,2016,8.0,4.0,2016.0,NaN,NaN,NaN,4
16944,8792,EMEA,Austria,1,1,1,1,0,Bureaucratic_Code_4,2016-01-15,...,28,3,2016,31.0,3.0,2016.0,NaN,NaN,NaN,3
16945,28561,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-10-20,...,25,4,2016,29.0,4.0,2016.0,NaN,NaN,NaN,4
16946,28318,Americas,NE America,1,1,1,1,0,Bureaucratic_Code_4,2015-09-03,...,1,7,2016,31.0,8.0,2016.0,NaN,NaN,NaN,7

In [148]:
df_2

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Planned_Delivery_Start_Date_Day,Planned_Delivery_Start_Date_Month,Planned_Delivery_Start_Date_Year,Planned_Delivery_End_Date_Day,Planned_Delivery_End_Date_Month,Planned_Delivery_End_Date_Year,Actual_Delivery_Date_Day,Actual_Delivery_Date_Month,Actual_Delivery_Date_Year,Delivery_Month
0,6140,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,5,2019,31.0,5.0,2019.0,NaN,NaN,NaN,5
1,6146,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,5,2019,31.0,5.0,2019.0,NaN,NaN,NaN,5
2,6151,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,5,2019,31.0,5.0,2019.0,NaN,NaN,NaN,5
3,6118,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,6,2019,28.0,6.0,2019.0,NaN,NaN,NaN,6
4,6124,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,6,2019,29.0,6.0,2019.0,NaN,NaN,NaN,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2546,16345,EMEA,KSA,1,1,0,0,0,Bureaucratic_Code_4,2017-06-12,...,1,5,2019,10.0,5.0,2019.0,NaN,NaN,NaN,5
2547,15218,Americas,SE America,1,1,0,0,0,Bureaucratic_Code_4,2018-06-08,...,1,10,2019,31.0,12.0,2019.0,NaN,NaN,NaN,10
2548,15224,Americas,SE America,1,1,1,1,0,Bureaucratic_Code_4,2018-06-08,...,1,10,2019,31.0,12.0,2019.0,NaN,NaN,NaN,10
2549,7286,Americas,NE America,1,1,0,0,0,Bureaucratic_Code_4,2018-08-29,...,1,8,2019,1.0,8.0,2019.0,NaN,NaN,NaN,8
2550,11263,EMEA,Belgium,1,0,0,0,0,Bureaucratic_Code_5,2016-03-03,...,21,10,2019,13.0,12.0,2019.0,NaN,NaN,NaN,10

## Codificación de algunas variables categoricas

In [149]:
import category_encoders as ce
encoder_family=ce.BinaryEncoder(cols=['Product_Family'])
vertical_stack_bin1=encoder_family.fit_transform(vertical_stack['Product_Family'])
vertical_stack_bin1=vertical_stack_bin1.add_prefix('Bit_')

encoder_name=ce.BinaryEncoder(cols=['Product_Name'])
vertical_stack_bin2=encoder_name.fit_transform(vertical_stack['Product_Name'])
vertical_stack_bin2=vertical_stack_bin2.add_prefix('Bit_')

vertical_stack_encodeado=pd.concat([vertical_stack,vertical_stack_bin1,vertical_stack_bin2],axis=1)
vertical_stack_encodeado.head()

/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Bit_Product_Name_0,Bit_Product_Name_1,Bit_Product_Name_2,Bit_Product_Name_3,Bit_Product_Name_4,Bit_Product_Name_5,Bit_Product_Name_6,Bit_Product_Name_7,Bit_Product_Name_8,Bit_Product_Name_9
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,0,0,0,0,0,0,0,0,0,1
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,0,0,0,0,0,0,0,0,1,0
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,0,0,0,0,0,0,0,0,1,1
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,0,0,0,0,0,0,0,1,0,0
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,0,0,0,0,0,0,0,1,0,0

In [150]:
vertical_stack_encodeado

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Bit_Product_Name_0,Bit_Product_Name_1,Bit_Product_Name_2,Bit_Product_Name_3,Bit_Product_Name_4,Bit_Product_Name_5,Bit_Product_Name_6,Bit_Product_Name_7,Bit_Product_Name_8,Bit_Product_Name_9
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,0,0,0,0,0,0,0,0,0,1
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,0,0,0,0,0,0,0,0,1,0
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,0,0,0,0,0,0,0,0,1,1
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,0,0,0,0,0,0,0,1,0,0
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2546,16345,EMEA,KSA,1,1,0,0,0,Bureaucratic_Code_4,2017-06-12,...,0,0,1,0,0,1,1,0,0,0
2547,15218,Americas,SE America,1,1,0,0,0,Bureaucratic_Code_4,2018-06-08,...,0,1,1,0,1,1,1,0,1,0
2548,15224,Americas,SE America,1,1,1,1,0,Bureaucratic_Code_4,2018-06-08,...,0,1,1,0,1,1,1,0,1,0
2549,7286,Americas,NE America,1,1,0,0,0,Bureaucratic_Code_4,2018-08-29,...,0,1,1,1,0,0,1,0,1,1
2550,11263,EMEA,Belgium,1,0,0,0,0,Bureaucratic_Code_5,2016-03-03,...,0,1,1,1,1,1,0,0,1,0

## Codificación de algunas variables categoricas

Cada oportunidad puede tener más de un item 
y en particular los items tienen dos variables categoricas que son el nombre y la familia.
Cuando agrupemos por oportunidad buscaremos valores representativos de todos los items asociados a esa oportunidad.
Generalmente aplicamos funciones numericas, motivo por el cual necesitaremos codificar estas dos variables categóricas como números.

In [151]:
import category_encoders as ce
encoder_family=ce.BinaryEncoder(cols=['Product_Family'])
df_train_bin1=encoder_family.fit_transform(df_train['Product_Family'])
df_train_bin1=df_train_bin1.add_prefix('Bit_')

encoder_name=ce.BinaryEncoder(cols=['Product_Name'])
df_train_bin2=encoder_name.fit_transform(df_train['Product_Name'])
df_train_bin2=df_train_bin2.add_prefix('Bit_')

df_train_encodeado=pd.concat([df_train,df_train_bin1,df_train_bin2],axis=1)
df_train_encodeado.head()

#from sklearn.preprocessing import LabelBinarizer
#lb = LabelBinarizer()
#df_train_bin=lb.fit_transform(df_train['Product_Family'])
#pd.concat([df_train,pd.DataFrame(df_train_bin)],axis=1)

/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Bit_Product_Name_0,Bit_Product_Name_1,Bit_Product_Name_2,Bit_Product_Name_3,Bit_Product_Name_4,Bit_Product_Name_5,Bit_Product_Name_6,Bit_Product_Name_7,Bit_Product_Name_8,Bit_Product_Name_9
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,0,0,0,0,0,0,0,0,0,1
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,0,0,0,0,0,0,0,0,1,0
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,0,0,0,0,0,0,0,0,1,1
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,0,0,0,0,0,0,0,1,0,0
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,0,0,0,0,0,0,0,1,0,0

In [152]:
df_test_bin1=encoder_family.fit_transform(df_test['Product_Family'])
df_test_bin1=df_test_bin1.add_prefix('Bit_')

df_test_bin2=encoder_name.fit_transform(df_test['Product_Name'])
df_test_bin2=df_test_bin2.add_prefix('Bit_')

df_test_encodeado=pd.concat([df_test,df_test_bin1,df_test_bin2],axis=1)
df_test_encodeado.head()

/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Bit_Product_Family_7,Bit_Product_Name_0,Bit_Product_Name_1,Bit_Product_Name_2,Bit_Product_Name_3,Bit_Product_Name_4,Bit_Product_Name_5,Bit_Product_Name_6,Bit_Product_Name_7,Bit_Product_Name_8
0,6140,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,0,0,0,0,0,0,0,0,1
1,6146,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,0,0,0,0,0,0,0,0,1,0
2,6151,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,0,0,0,0,0,0,0,1,1
3,6118,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,0,0,0,0,0,0,1,0,0
4,6124,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,0,0,0,0,0,0,0,0,1,0

### Chequeo de nombres de columnas

In [153]:
df_test_encodeado.columns

Index(['ID', 'Region', 'Territory', 'Pricing, Delivery_Terms_Quote_Appr',
       'Pricing, Delivery_Terms_Approved', 'Bureaucratic_Code_0_Approval',
       'Bureaucratic_Code_0_Approved', 'Submitted_for_Approval',
       'Bureaucratic_Code', 'Account_Created_Date', 'Source ',
       'Billing_Country', 'Account_Name', 'Opportunity_Name', 'Opportunity_ID',
       'Sales_Contract_No', 'Account_Owner', 'Opportunity_Owner',
       'Account_Type', 'Opportunity_Type', 'Quote_Type', 'Delivery_Terms',
       'Opportunity_Created_Date', 'Brand', 'Product_Type', 'Size',
       'Product_Category_B', 'Price', 'Currency', 'Last_Activity',
       'Quote_Expiry_Date', 'Last_Modified_Date', 'Last_Modified_By',
       'Product_Family', 'Product_Name', 'ASP_Currency', 'ASP',
       'ASP_(converted)_Currency', 'ASP_(converted)',
       'Planned_Delivery_Start_Date', 'Planned_Delivery_End_Date', 'Month',
       'Delivery_Quarter', 'Delivery_Year', 'Actual_Delivery_Date', 'TRF',
       'Total_Amount_Currency', 'Total_Amount',
       'Total_Taxable_Amount_Currency', 'Total_Taxable_Amount',
       'Prod_Category_A', 'Account_Created_Date_Day',
       'Account_Created_Date_Month', 'Account_Created_Date_Year',
       'Opportunity_Created_Date_Day', 'Opportunity_Created_Date_Month',
       'Opportunity_Created_Date_Year', 'Last_Activity_Day',
       'Last_Activity_Month', 'Last_Activity_Year', 'Quote_Expiry_Date_Day',
       'Quote_Expiry_Date_Month', 'Quote_Expiry_Date_Year',
       'Last_Modified_Date_Day', 'Last_Modified_Date_Month',
       'Last_Modified_Date_Year', 'Planned_Delivery_Start_Date_Day',
       'Planned_Delivery_Start_Date_Month', 'Planned_Delivery_Start_Date_Year',
       'Planned_Delivery_End_Date_Day', 'Planned_Delivery_End_Date_Month',
       'Planned_Delivery_End_Date_Year', 'Actual_Delivery_Date_Day',
       'Actual_Delivery_Date_Month', 'Actual_Delivery_Date_Year',
       'Delivery_Month', 'Bit_Product_Family_0', 'Bit_Product_Family_1',
       'Bit_Product_Family_2', 'Bit_Product_Family_3', 'Bit_Product_Family_4',
       'Bit_Product_Family_5', 'Bit_Product_Family_6', 'Bit_Product_Family_7',
       'Bit_Product_Name_0', 'Bit_Product_Name_1', 'Bit_Product_Name_2',
       'Bit_Product_Name_3', 'Bit_Product_Name_4', 'Bit_Product_Name_5',
       'Bit_Product_Name_6', 'Bit_Product_Name_7', 'Bit_Product_Name_8'],
      dtype='object')

In [154]:
df_train_encodeado.columns

Index(['ID', 'Region', 'Territory', 'Pricing, Delivery_Terms_Quote_Appr',
       'Pricing, Delivery_Terms_Approved', 'Bureaucratic_Code_0_Approval',
       'Bureaucratic_Code_0_Approved', 'Submitted_for_Approval',
       'Bureaucratic_Code', 'Account_Created_Date', 'Source ',
       'Billing_Country', 'Account_Name', 'Opportunity_Name', 'Opportunity_ID',
       'Sales_Contract_No', 'Account_Owner', 'Opportunity_Owner',
       'Account_Type', 'Opportunity_Type', 'Quote_Type', 'Delivery_Terms',
       'Opportunity_Created_Date', 'Brand', 'Product_Type', 'Size',
       'Product_Category_B', 'Price', 'Currency', 'Last_Activity',
       'Quote_Expiry_Date', 'Last_Modified_Date', 'Last_Modified_By',
       'Product_Family', 'Product_Name', 'ASP_Currency', 'ASP',
       'ASP_(converted)_Currency', 'ASP_(converted)',
       'Planned_Delivery_Start_Date', 'Planned_Delivery_End_Date', 'Month',
       'Delivery_Quarter', 'Delivery_Year', 'Actual_Delivery_Date', 'TRF',
       'Total_Amount_Currency', 'Total_Amount',
       'Total_Taxable_Amount_Currency', 'Total_Taxable_Amount', 'Stage',
       'Prod_Category_A', 'Account_Created_Date_Day',
       'Account_Created_Date_Month', 'Account_Created_Date_Year',
       'Opportunity_Created_Date_Day', 'Opportunity_Created_Date_Month',
       'Opportunity_Created_Date_Year', 'Last_Activity_Day',
       'Last_Activity_Month', 'Last_Activity_Year', 'Quote_Expiry_Date_Day',
       'Quote_Expiry_Date_Month', 'Quote_Expiry_Date_Year',
       'Last_Modified_Date_Day', 'Last_Modified_Date_Month',
       'Last_Modified_Date_Year', 'Planned_Delivery_Start_Date_Day',
       'Planned_Delivery_Start_Date_Month', 'Planned_Delivery_Start_Date_Year',
       'Planned_Delivery_End_Date_Day', 'Planned_Delivery_End_Date_Month',
       'Planned_Delivery_End_Date_Year', 'Actual_Delivery_Date_Day',
       'Actual_Delivery_Date_Month', 'Actual_Delivery_Date_Year',
       'Delivery_Month', 'Bit_Product_Family_0', 'Bit_Product_Family_1',
       'Bit_Product_Family_2', 'Bit_Product_Family_3', 'Bit_Product_Family_4',
       'Bit_Product_Family_5', 'Bit_Product_Family_6', 'Bit_Product_Family_7',
       'Bit_Product_Family_8', 'Bit_Product_Name_0', 'Bit_Product_Name_1',
       'Bit_Product_Name_2', 'Bit_Product_Name_3', 'Bit_Product_Name_4',
       'Bit_Product_Name_5', 'Bit_Product_Name_6', 'Bit_Product_Name_7',
       'Bit_Product_Name_8', 'Bit_Product_Name_9'],
      dtype='object')

In [155]:
#df_train_encodeado.info()

In [156]:
#df_test_encodeado.info()

In [157]:
vertical_stack_encodeado.columns

Index(['ID', 'Region', 'Territory', 'Pricing, Delivery_Terms_Quote_Appr',
       'Pricing, Delivery_Terms_Approved', 'Bureaucratic_Code_0_Approval',
       'Bureaucratic_Code_0_Approved', 'Submitted_for_Approval',
       'Bureaucratic_Code', 'Account_Created_Date', 'Source ',
       'Billing_Country', 'Account_Name', 'Opportunity_Name', 'Opportunity_ID',
       'Sales_Contract_No', 'Account_Owner', 'Opportunity_Owner',
       'Account_Type', 'Opportunity_Type', 'Quote_Type', 'Delivery_Terms',
       'Opportunity_Created_Date', 'Brand', 'Product_Type', 'Size',
       'Product_Category_B', 'Price', 'Currency', 'Last_Activity',
       'Quote_Expiry_Date', 'Last_Modified_Date', 'Last_Modified_By',
       'Product_Family', 'Product_Name', 'ASP_Currency', 'ASP',
       'ASP_(converted)_Currency', 'ASP_(converted)',
       'Planned_Delivery_Start_Date', 'Planned_Delivery_End_Date', 'Month',
       'Delivery_Quarter', 'Delivery_Year', 'Actual_Delivery_Date', 'TRF',
       'Total_Amount_Currency', 'Total_Amount',
       'Total_Taxable_Amount_Currency', 'Total_Taxable_Amount', 'Stage',
       'Prod_Category_A', 'Account_Created_Date_Day',
       'Account_Created_Date_Month', 'Account_Created_Date_Year',
       'Opportunity_Created_Date_Day', 'Opportunity_Created_Date_Month',
       'Opportunity_Created_Date_Year', 'Last_Activity_Day',
       'Last_Activity_Month', 'Last_Activity_Year', 'Quote_Expiry_Date_Day',
       'Quote_Expiry_Date_Month', 'Quote_Expiry_Date_Year',
       'Last_Modified_Date_Day', 'Last_Modified_Date_Month',
       'Last_Modified_Date_Year', 'Planned_Delivery_Start_Date_Day',
       'Planned_Delivery_Start_Date_Month', 'Planned_Delivery_Start_Date_Year',
       'Planned_Delivery_End_Date_Day', 'Planned_Delivery_End_Date_Month',
       'Planned_Delivery_End_Date_Year', 'Actual_Delivery_Date_Day',
       'Actual_Delivery_Date_Month', 'Actual_Delivery_Date_Year',
       'Delivery_Month', 'Bit_Product_Family_0', 'Bit_Product_Family_1',
       'Bit_Product_Family_2', 'Bit_Product_Family_3', 'Bit_Product_Family_4',
       'Bit_Product_Family_5', 'Bit_Product_Family_6', 'Bit_Product_Family_7',
       'Bit_Product_Family_8', 'Bit_Product_Name_0', 'Bit_Product_Name_1',
       'Bit_Product_Name_2', 'Bit_Product_Name_3', 'Bit_Product_Name_4',
       'Bit_Product_Name_5', 'Bit_Product_Name_6', 'Bit_Product_Name_7',
       'Bit_Product_Name_8', 'Bit_Product_Name_9'],
      dtype='object')

In [158]:
df_train_encodeado = vertical_stack_encodeado.iloc[:16947,:] 
df_test_encodeado = vertical_stack_encodeado.iloc[16947:,:]

## Agrupamiento de los datos por Opportunity_ID

In [159]:
test_agrupado = df_test_encodeado.groupby([
'Region',
'Territory',
'Pricing, Delivery_Terms_Quote_Appr',
'Pricing, Delivery_Terms_Approved',
'Bureaucratic_Code_0_Approval',
'Bureaucratic_Code_0_Approved',
'Submitted_for_Approval',
'Bureaucratic_Code',
#'Account_Created_Date',
'Account_Created_Date_Day',
'Account_Created_Date_Month',
'Account_Created_Date_Year',
'Source ',
'Billing_Country',
'Account_Name',
'Opportunity_Name',
'Opportunity_ID',
'Sales_Contract_No',
'Account_Owner',
'Opportunity_Owner',
'Account_Type',
'Opportunity_Type',
'Quote_Type',
'Delivery_Terms',
#'Opportunity_Created_Date',
'Opportunity_Created_Date_Day', 
'Opportunity_Created_Date_Month',
'Opportunity_Created_Date_Year', 
'Brand',
'Product_Type',
'Size',
'Product_Category_B',
'Price',
'Currency',
#'Last_Modified_Date',
'Last_Modified_Date_Day', 
'Last_Modified_Date_Month',
'Last_Modified_Date_Year', 
'Last_Modified_By',    
'Total_Amount_Currency',
'Total_Taxable_Amount_Currency',
'Total_Taxable_Amount',
#'Stage',  #test no tiene stage (que es la columna a predecir)
'Prod_Category_A'
    
]).agg(
                                  {'TRF': ['mean','std','min','max'], 
                                   'Total_Amount': ['mean','std','min','max'],
                                   
                                   #'Last_Activity':['min','max'],#esta columna tiene todos valores null 
                                                                 #ver si conviene sacarla        

                                   'Last_Activity_Day': ['mean','std','min','max'],
                                   'Last_Activity_Month': ['mean','std','min','max'], 
                                   'Last_Activity_Year': ['mean','std','min','max'], 
                                   
                                   #'Quote_Expiry_Date':['min','max'],
                                   'Quote_Expiry_Date_Day': ['mean','std','min','max'],
                                   'Quote_Expiry_Date_Month': ['mean','std','min','max'], 
                                   'Quote_Expiry_Date_Year': ['mean','std','min','max'],
                                   
                                   #'Product_Family':?,
                                   #'Product_Name':?,
                                   'Bit_Product_Family_0': ['mean','std','min','max'], 
                                   'Bit_Product_Family_1': ['mean','std','min','max'],
                                   'Bit_Product_Family_2': ['mean','std','min','max'], 
                                   'Bit_Product_Family_3': ['mean','std','min','max'], 
                                   'Bit_Product_Family_4': ['mean','std','min','max'],
                                   'Bit_Product_Family_5': ['mean','std','min','max'], 
                                   'Bit_Product_Family_6': ['mean','std','min','max'], 
                                   'Bit_Product_Family_7': ['mean','std','min','max'],
                                   'Bit_Product_Family_8': ['mean','std','min','max'],
                                   
                                   'Bit_Product_Name_0': ['mean','std','min','max'], 
                                   'Bit_Product_Name_1': ['mean','std','min','max'], 
                                   'Bit_Product_Name_2': ['mean','std','min','max'],
                                   'Bit_Product_Name_3': ['mean','std','min','max'], 
                                   'Bit_Product_Name_4': ['mean','std','min','max'], 
                                   'Bit_Product_Name_5': ['mean','std','min','max'],
                                   'Bit_Product_Name_6': ['mean','std','min','max'], 
                                   'Bit_Product_Name_7': ['mean','std','min','max'], 
                                   'Bit_Product_Name_8': ['mean','std','min','max'],
                                   'Bit_Product_Name_9': ['mean','std','min','max'],
                                   
                                   'ASP':['mean','std','min','max'],
                                   'ASP_Currency':'max',
                                   'ASP_(converted)': ['mean','std','min','max'],
                                   'ASP_(converted)_Currency':'max',
                                   
                                   'Delivery_Quarter':['mean','std','min','max'],
                                   'Delivery_Year':['mean','std','min','max'],
                                   'Delivery_Month':['mean','std','min','max'],
                                   #'Actual_Delivery_Date':['min','max'],#esta columna tienen todos valores null 
                                                                         #ver si conviene sacarla
                                   'Actual_Delivery_Date_Day':['mean','std','min','max'],
                                   'Actual_Delivery_Date_Month': ['mean','std','min','max'],
                                   'Actual_Delivery_Date_Year':['mean','std','min','max'],
                                   
                                   #'Planned_Delivery_Start_Date':['min','max'],
                                   'Planned_Delivery_Start_Date_Day':['mean','std','min','max'],
                                   'Planned_Delivery_Start_Date_Month':['mean','std','min','max'], 
                                   'Planned_Delivery_Start_Date_Year':['mean','std','min','max'],
                                   #'Planned_Delivery_End_Date':['min','max'],
                                   'Planned_Delivery_End_Date_Day':['mean','std','min','max'], 
                                   'Planned_Delivery_End_Date_Month':['mean','std','min','max'],
                                   'Planned_Delivery_End_Date_Year':['mean','std','min','max'],                                    
                                   
                                   'Opportunity_ID':'count' #cantidad de items por oportunidad
                                  })#.reset_index()

#lo que quiero es agrupar por opportunity_ID y categoricos iguales y promediar los numericos

#df_train.dtypes
#transformo los multiindices en un indice de un solo nivel
test_level0=test_agrupado.columns.get_level_values(0)
test_level1=test_agrupado.columns.get_level_values(1)
test_agrupado.columns=test_level0+'_'+test_level1
test_agrupado.reset_index(inplace=True)
test_agrupado.rename(columns={'Opportunity_ID_count':'Items_by_opportunity'},inplace=True)
test_agrupado.rename(columns={'ASP_Currency_max':'ASP_Currency'},inplace=True)
test_agrupado.rename(columns={'ASP_(converted)_Currency_max':'ASP_(converted)_Currency'},inplace=True)
test_agrupado

,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date_Day,Account_Created_Date_Month,...,Planned_Delivery_End_Date_Day_max,Planned_Delivery_End_Date_Month_mean,Planned_Delivery_End_Date_Month_std,Planned_Delivery_End_Date_Month_min,Planned_Delivery_End_Date_Month_max,Planned_Delivery_End_Date_Year_mean,Planned_Delivery_End_Date_Year_std,Planned_Delivery_End_Date_Year_min,Planned_Delivery_End_Date_Year_max,Items_by_opportunity
0,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,20,2,...,31.0,12.0,0.0,12.0,12.0,2019.0,0.0,2019.0,2019.0,2
1,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,22,8,...,31.0,12.0,NaN,12.0,12.0,2019.0,NaN,2019.0,2019.0,1
2,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,22,8,...,31.0,3.0,0.0,3.0,3.0,2019.0,0.0,2019.0,2019.0,8
3,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,4,4,...,28.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,9
4,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,4,4,...,28.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1562,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,21,8,...,30.0,4.0,NaN,4.0,4.0,2019.0,NaN,2019.0,2019.0,1
1563,Middle East,KSA,1,1,0,0,0,Bureaucratic_Code_4,17,10,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1564,Middle East,KSA,1,1,1,1,0,Bureaucratic_Code_4,15,10,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1565,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,28,12,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1566,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,28,12,...,1.0,6.0,NaN,6.0,6.0,2019.0,NaN,2019.0,2019.0,1

In [160]:
train_agrupado = df_train_encodeado.groupby([
'Region',
'Territory',
'Pricing, Delivery_Terms_Quote_Appr',
'Pricing, Delivery_Terms_Approved',
'Bureaucratic_Code_0_Approval',
'Bureaucratic_Code_0_Approved',
'Submitted_for_Approval',
'Bureaucratic_Code',
#'Account_Created_Date',
'Account_Created_Date_Day',
'Account_Created_Date_Month',
'Account_Created_Date_Year',
'Source ',
'Billing_Country',
'Account_Name',
'Opportunity_Name',
'Opportunity_ID',
'Sales_Contract_No',
'Account_Owner',
'Opportunity_Owner',
'Account_Type',
'Opportunity_Type',
'Quote_Type',
'Delivery_Terms',
#'Opportunity_Created_Date',
'Opportunity_Created_Date_Day', 
'Opportunity_Created_Date_Month',
'Opportunity_Created_Date_Year', 
'Brand',
'Product_Type',
'Size',
'Product_Category_B',
'Price',
'Currency',
#'Last_Modified_Date',
'Last_Modified_Date_Day', 
'Last_Modified_Date_Month',
'Last_Modified_Date_Year', 
'Last_Modified_By',    
'Total_Amount_Currency',
'Total_Taxable_Amount_Currency',
'Total_Taxable_Amount',
'Stage',  
'Prod_Category_A'
    
]).agg(
                                  {'TRF': ['mean','std','min','max'], 
                                   'Total_Amount': ['mean','std','min','max'],
                                   
                                   #'Last_Activity':['min','max'],#esta columna tiene todos valores null 
                                                                 #ver si conviene sacarla        

                                   'Last_Activity_Day': ['mean','std','min','max'],
                                   'Last_Activity_Month': ['mean','std','min','max'], 
                                   'Last_Activity_Year': ['mean','std','min','max'], 
                                   
                                   #'Quote_Expiry_Date':['min','max'],
                                   'Quote_Expiry_Date_Day': ['mean','std','min','max'],
                                   'Quote_Expiry_Date_Month': ['mean','std','min','max'], 
                                   'Quote_Expiry_Date_Year': ['mean','std','min','max'],
                                   
                                   #'Product_Family':?,
                                   #'Product_Name':?,
                                   'Bit_Product_Family_0': ['mean','std','min','max'], 
                                   'Bit_Product_Family_1': ['mean','std','min','max'],
                                   'Bit_Product_Family_2': ['mean','std','min','max'], 
                                   'Bit_Product_Family_3': ['mean','std','min','max'], 
                                   'Bit_Product_Family_4': ['mean','std','min','max'],
                                   'Bit_Product_Family_5': ['mean','std','min','max'], 
                                   'Bit_Product_Family_6': ['mean','std','min','max'], 
                                   'Bit_Product_Family_7': ['mean','std','min','max'],
                                   'Bit_Product_Family_8': ['mean','std','min','max'],
                                   
                                   'Bit_Product_Name_0': ['mean','std','min','max'], 
                                   'Bit_Product_Name_1': ['mean','std','min','max'], 
                                   'Bit_Product_Name_2': ['mean','std','min','max'],
                                   'Bit_Product_Name_3': ['mean','std','min','max'], 
                                   'Bit_Product_Name_4': ['mean','std','min','max'], 
                                   'Bit_Product_Name_5': ['mean','std','min','max'],
                                   'Bit_Product_Name_6': ['mean','std','min','max'], 
                                   'Bit_Product_Name_7': ['mean','std','min','max'], 
                                   'Bit_Product_Name_8': ['mean','std','min','max'],
                                   'Bit_Product_Name_9': ['mean','std','min','max'],
                                   
                                   'ASP':['mean','std','min','max'],
                                   'ASP_Currency':'max',
                                   'ASP_(converted)': ['mean','std','min','max'],
                                   'ASP_(converted)_Currency':'max',
                                   
                                   'Delivery_Quarter':['mean','std','min','max'],
                                   'Delivery_Year':['mean','std','min','max'],
                                   'Delivery_Month':['mean','std','min','max'],

                                   #'Actual_Delivery_Date':['min','max'],#esta columna tienen todos valores null 
                                                                         #ver si conviene sacarla
                                   'Actual_Delivery_Date_Day':['mean','std','min','max'],
                                   'Actual_Delivery_Date_Month': ['mean','std','min','max'],
                                   'Actual_Delivery_Date_Year':['mean','std','min','max'],
                                   
                                   #'Planned_Delivery_Start_Date':['min','max'],
                                   'Planned_Delivery_Start_Date_Day':['mean','std','min','max'],
                                   'Planned_Delivery_Start_Date_Month':['mean','std','min','max'], 
                                   'Planned_Delivery_Start_Date_Year':['mean','std','min','max'],
                                   #'Planned_Delivery_End_Date':['min','max'],
                                   'Planned_Delivery_End_Date_Day':['mean','std','min','max'], 
                                   'Planned_Delivery_End_Date_Month':['mean','std','min','max'],
                                   'Planned_Delivery_End_Date_Year':['mean','std','min','max'],    
                                   'Opportunity_ID':'count' #cantidad de items por oportunidad
                                  })#.reset_index()

#lo que quiero es agrupar por opportunity_ID y categoricos iguales y promediar los numericos

#df_train.dtypes
#transformo los multiindices en un indice de un solo nivel
train_level0=train_agrupado.columns.get_level_values(0)
train_level1=train_agrupado.columns.get_level_values(1)
train_agrupado.columns=train_level0+'_'+train_level1
train_agrupado.reset_index(inplace=True)
train_agrupado.rename(columns={'Opportunity_ID_count':'Items_by_opportunity'},inplace=True)
train_agrupado.rename(columns={'ASP_Currency_max':'ASP_Currency'},inplace=True)
train_agrupado.rename(columns={'ASP_(converted)_Currency_max':'ASP_(converted)_Currency'},inplace=True)

train_agrupado

,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date_Day,Account_Created_Date_Month,...,Planned_Delivery_End_Date_Day_max,Planned_Delivery_End_Date_Month_mean,Planned_Delivery_End_Date_Month_std,Planned_Delivery_End_Date_Month_min,Planned_Delivery_End_Date_Month_max,Planned_Delivery_End_Date_Year_mean,Planned_Delivery_End_Date_Year_std,Planned_Delivery_End_Date_Year_min,Planned_Delivery_End_Date_Year_max,Items_by_opportunity
0,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,11.0,NaN,11.0,11.0,2017.0,NaN,2017.0,2017.0,1
1,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,15.0,12.0,NaN,12.0,12.0,2017.0,NaN,2017.0,2017.0,1
2,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,11.0,NaN,11.0,11.0,2017.0,NaN,2017.0,2017.0,1
3,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,6.0,NaN,6.0,6.0,2017.0,NaN,2017.0,2017.0,1
4,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,19,9,...,29.0,12.0,NaN,12.0,12.0,2017.0,NaN,2017.0,2017.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9836,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,24,1,...,28.0,2.0,NaN,2.0,2.0,2017.0,NaN,2017.0,2017.0,1
9837,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,28,10,...,15.0,12.0,NaN,12.0,12.0,2018.0,NaN,2018.0,2018.0,1
9838,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,28,10,...,1.0,4.0,NaN,4.0,4.0,2019.0,NaN,2019.0,2019.0,1
9839,Middle East,UAE (Others),1,1,1,1,0,Bureaucratic_Code_1,3,7,...,31.0,8.0,NaN,8.0,8.0,2018.0,NaN,2018.0,2018.0,1
9840,Middle East,UAE (Others),1,1,1,1,0,Bureaucratic_Code_4,13,10,...,23.0,12.0,NaN,12.0,12.0,2016.0,NaN,2016.0,2016.0,1

In [161]:
#genero el CSV
test_agrupado.to_csv(r'./Test_Preprocesado_TP2_Datos_2020-2C-b.csv',index=False , header=True)
train_agrupado.to_csv(r'./Train_Preprocesado_TP2_Datos_2020-2C-b.csv',index=False , header=True)

### Chequeo de dimensiones del set de datos luego de procesarlo

In [162]:
print ("dimensiones del set de test antes de procesarlo:",df_test.shape)
print ("dimensiones del set de test despues de procesarlo:",test_agrupado.shape)

dimensiones del set de test antes de procesarlo: (2551, 76)
dimensiones del set de test despues de procesarlo: (1567, 207)

In [163]:
print ("dimensiones del set de test antes de procesarlo:",df_train.shape)
print ("dimensiones del set de test despues de procesarlo:",train_agrupado.shape)

dimensiones del set de test antes de procesarlo: (16947, 77)
dimensiones del set de test despues de procesarlo: (9841, 208)

In [164]:
test_agrupado.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1567 entries, 0 to 1566
Data columns (total 207 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   Region                                  object
 1   Territory                               object
 2   Pricing, Delivery_Terms_Quote_Appr      int64
 3   Pricing, Delivery_Terms_Approved        int64
 4   Bureaucratic_Code_0_Approval            int64
 5   Bureaucratic_Code_0_Approved            int64
 6   Submitted_for_Approval                  int64
 7   Bureaucratic_Code                       object
 8   Account_Created_Date_Day                int64
 9   Account_Created_Date_Month              int64
 10  Account_Created_Date_Year               int64
 11  Source                                  object
 12  Billing_Country                         object
 13  Account_Name                            object
 14  Opportunity_Name                        object
 15  Opportunity_ID                          int64
 16  Sales_Contract_No                       object
 17  Account_Owner                           object
 18  Opportunity_Owner                       object
 19  Account_Type                            object
 20  Opportunity_Type                        object
 21  Quote_Type                              object
 22  Delivery_Terms                          object
 23  Opportunity_Created_Date_Day            int64
 24  Opportunity_Created_Date_Month          int64
 25  Opportunity_Created_Date_Year           int64
 26  Brand                                   object
 27  Product_Type                            object
 28  Size                                    object
 29  Product_Category_B                      object
 30  Price                                   object
 31  Currency                                object
 32  Last_Modified_Date_Day                  int64
 33  Last_Modified_Date_Month                int64
 34  Last_Modified_Date_Year                 int64
 35  Last_Modified_By                        object
 36  Total_Amount_Currency                   object
 37  Total_Taxable_Amount_Currency           object
 38  Total_Taxable_Amount                    float64
 39  Prod_Category_A                         object
 40  TRF_mean                                float64
 41  TRF_std                                 float64
 42  TRF_min                                 int64
 43  TRF_max                                 int64
 44  Total_Amount_mean                       float64
 45  Total_Amount_std                        float64
 46  Total_Amount_min                        float64
 47  Total_Amount_max                        float64
 48  Last_Activity_Day_mean                  float64
 49  Last_Activity_Day_std                   float64
 50  Last_Activity_Day_min                   float64
 51  Last_Activity_Day_max                   float64
 52  Last_Activity_Month_mean                float64
 53  Last_Activity_Month_std                 float64
 54  Last_Activity_Month_min                 float64
 55  Last_Activity_Month_max                 float64
 56  Last_Activity_Year_mean                 float64
 57  Last_Activity_Year_std                  float64
 58  Last_Activity_Year_min                  float64
 59  Last_Activity_Year_max                  float64
 60  Quote_Expiry_Date_Day_mean              float64
 61  Quote_Expiry_Date_Day_std               float64
 62  Quote_Expiry_Date_Day_min               float64
 63  Quote_Expiry_Date_Day_max               float64
 64  Quote_Expiry_Date_Month_mean            float64
 65  Quote_Expiry_Date_Month_std             float64
 66  Quote_Expiry_Date_Month_min             float64
 67  Quote_Expiry_Date_Month_max             float64
 68  Quote_Expiry_Date_Year_mean             float64
 69  Quote_Expiry_Date_Year_std              float64
 70  Quote_Expiry_Date_Year_min              float64
 71  Quote_Expiry_Date_Year_max              float64
 72  Bit_Product_Family_0_mean               int64
 73  Bit_Product_Family_0_std                float64
 74  Bit_Product_Family_0_min                int64
 75  Bit_Product_Family_0_max                int64
 76  Bit_Product_Family_1_mean               float64
 77  Bit_Product_Family_1_std                float64
 78  Bit_Product_Family_1_min                int64
 79  Bit_Product_Family_1_max                int64
 80  Bit_Product_Family_2_mean               float64
 81  Bit_Product_Family_2_std                float64
 82  Bit_Product_Family_2_min                int64
 83  Bit_Product_Family_2_max                int64
 84  Bit_Product_Family_3_mean               float64
 85  Bit_Product_Family_3_std                float64
 86  Bit_Product_Family_3_min                int64
 87  Bit_Product_Family_3_max                int64
 88  Bit_Product_Family_4_mean               float64
 89  Bit_Product_Family_4_std                float64
 90  Bit_Product_Family_4_min                int64
 91  Bit_Product_Family_4_max                int64
 92  Bit_Product_Family_5_mean               float64
 93  Bit_Product_Family_5_std                float64
 94  Bit_Product_Family_5_min                int64
 95  Bit_Product_Family_5_max                int64
 96  Bit_Product_Family_6_mean               float64
 97  Bit_Product_Family_6_std                float64
 98  Bit_Product_Family_6_min                int64
 99  Bit_Product_Family_6_max                int64
 100 Bit_Product_Family_7_mean               float64
 101 Bit_Product_Family_7_std                float64
 102 Bit_Product_Family_7_min                int64
 103 Bit_Product_Family_7_max                int64
 104 Bit_Product_Family_8_mean               float64
 105 Bit_Product_Family_8_std                float64
 106 Bit_Product_Family_8_min                int64
 107 Bit_Product_Family_8_max                int64
 108 Bit_Product_Name_0_mean                 int64
 109 Bit_Product_Name_0_std                  float64
 110 Bit_Product_Name_0_min                  int64
 111 Bit_Product_Name_0_max                  int64
 112 Bit_Product_Name_1_mean                 float64
 113 Bit_Product_Name_1_std                  float64
 114 Bit_Product_Name_1_min                  int64
 115 Bit_Product_Name_1_max                  int64
 116 Bit_Product_Name_2_mean                 float64
 117 Bit_Product_Name_2_std                  float64
 118 Bit_Product_Name_2_min                  int64
 119 Bit_Product_Name_2_max                  int64
 120 Bit_Product_Name_3_mean                 float64
 121 Bit_Product_Name_3_std                  float64
 122 Bit_Product_Name_3_min                  int64
 123 Bit_Product_Name_3_max                  int64
 124 Bit_Product_Name_4_mean                 float64
 125 Bit_Product_Name_4_std                  float64
 126 Bit_Product_Name_4_min                  int64
 127 Bit_Product_Name_4_max                  int64
 128 Bit_Product_Name_5_mean                 float64
 129 Bit_Product_Name_5_std                  float64
 130 Bit_Product_Name_5_min                  int64
 131 Bit_Product_Name_5_max                  int64
 132 Bit_Product_Name_6_mean                 float64
 133 Bit_Product_Name_6_std                  float64
 134 Bit_Product_Name_6_min                  int64
 135 Bit_Product_Name_6_max                  int64
 136 Bit_Product_Name_7_mean                 float64
 137 Bit_Product_Name_7_std                  float64
 138 Bit_Product_Name_7_min                  int64
 139 Bit_Product_Name_7_max                  int64
 140 Bit_Product_Name_8_mean                 float64
 141 Bit_Product_Name_8_std                  float64
 142 Bit_Product_Name_8_min                  int64
 143 Bit_Product_Name_8_max                  int64
 144 Bit_Product_Name_9_mean                 float64
 145 Bit_Product_Name_9_std                  float64
 146 Bit_Product_Name_9_min                  int64
 147 Bit_Product_Name_9_max                  int64
 148 ASP_mean                                float64
 149 ASP_std                                 float64
 150 ASP_min                                 float64
 151 ASP_max                                 float64
 152 ASP_Currency                            object
 153 ASP_(converted)_mean                    float64
 154 ASP_(converted)_std                     float64
 155 ASP_(converted)_min                     float64
 156 ASP_(converted)_max                     float64
 157 ASP_(converted)_Currency                object
 158 Delivery_Quarter_mean                   float64
 159 Delivery_Quarter_std                    float64
 160 Delivery_Quarter_min                    float64
 161 Delivery_Quarter_max                    float64
 162 Delivery_Year_mean                      float64
 163 Delivery_Year_std                       float64
 164 Delivery_Year_min                       int64
 165 Delivery_Year_max                       int64
 166 Delivery_Month_mean                     float64
 167 Delivery_Month_std                      float64
 168 Delivery_Month_min                      int8
 169 Delivery_Month_max                      int8
 170 Actual_Delivery_Date_Day_mean           float64
 171 Actual_Delivery_Date_Day_std            float64
 172 Actual_Delivery_Date_Day_min            float64
 173 Actual_Delivery_Date_Day_max            float64
 174 Actual_Delivery_Date_Month_mean         float64
 175 Actual_Delivery_Date_Month_std          float64
 176 Actual_Delivery_Date_Month_min          float64
 177 Actual_Delivery_Date_Month_max          float64
 178 Actual_Delivery_Date_Year_mean          float64
 179 Actual_Delivery_Date_Year_std           float64
 180 Actual_Delivery_Date_Year_min           float64
 181 Actual_Delivery_Date_Year_max           float64
 182 Planned_Delivery_Start_Date_Day_mean    float64
 183 Planned_Delivery_Start_Date_Day_std     float64
 184 Planned_Delivery_Start_Date_Day_min     int64
 185 Planned_Delivery_Start_Date_Day_max     int64
 186 Planned_Delivery_Start_Date_Month_mean  float64
 187 Planned_Delivery_Start_Date_Month_std   float64
 188 Planned_Delivery_Start_Date_Month_min   int64
 189 Planned_Delivery_Start_Date_Month_max   int64
 190 Planned_Delivery_Start_Date_Year_mean   float64
 191 Planned_Delivery_Start_Date_Year_std    float64
 192 Planned_Delivery_Start_Date_Year_min    int64
 193 Planned_Delivery_Start_Date_Year_max    int64
 194 Planned_Delivery_End_Date_Day_mean      float64
 195 Planned_Delivery_End_Date_Day_std       float64
 196 Planned_Delivery_End_Date_Day_min       float64
 197 Planned_Delivery_End_Date_Day_max       float64
 198 Planned_Delivery_End_Date_Month_mean    float64
 199 Planned_Delivery_End_Date_Month_std     float64
 200 Planned_Delivery_End_Date_Month_min     float64
 201 Planned_Delivery_End_Date_Month_max     float64
 202 Planned_Delivery_End_Date_Year_mean     float64
 203 Planned_Delivery_End_Date_Year_std      float64
 204 Planned_Delivery_End_Date_Year_min      float64
 205 Planned_Delivery_End_Date_Year_max      float64
 206 Items_by_opportunity                    int64
dtypes: float64(113), int64(66), int8(2), object(26)
memory usage: 2.5+ MB

In [165]:
train_agrupado.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9841 entries, 0 to 9840
Data columns (total 208 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   Region                                  object
 1   Territory                               object
 2   Pricing, Delivery_Terms_Quote_Appr      int64
 3   Pricing, Delivery_Terms_Approved        int64
 4   Bureaucratic_Code_0_Approval            int64
 5   Bureaucratic_Code_0_Approved            int64
 6   Submitted_for_Approval                  int64
 7   Bureaucratic_Code                       object
 8   Account_Created_Date_Day                int64
 9   Account_Created_Date_Month              int64
 10  Account_Created_Date_Year               int64
 11  Source                                  object
 12  Billing_Country                         object
 13  Account_Name                            object
 14  Opportunity_Name                        object
 15  Opportunity_ID                          int64
 16  Sales_Contract_No                       object
 17  Account_Owner                           object
 18  Opportunity_Owner                       object
 19  Account_Type                            object
 20  Opportunity_Type                        object
 21  Quote_Type                              object
 22  Delivery_Terms                          object
 23  Opportunity_Created_Date_Day            int64
 24  Opportunity_Created_Date_Month          int64
 25  Opportunity_Created_Date_Year           int64
 26  Brand                                   object
 27  Product_Type                            object
 28  Size                                    object
 29  Product_Category_B                      object
 30  Price                                   object
 31  Currency                                object
 32  Last_Modified_Date_Day                  int64
 33  Last_Modified_Date_Month                int64
 34  Last_Modified_Date_Year                 int64
 35  Last_Modified_By                        object
 36  Total_Amount_Currency                   object
 37  Total_Taxable_Amount_Currency           object
 38  Total_Taxable_Amount                    float64
 39  Stage                                   object
 40  Prod_Category_A                         object
 41  TRF_mean                                float64
 42  TRF_std                                 float64
 43  TRF_min                                 int64
 44  TRF_max                                 int64
 45  Total_Amount_mean                       float64
 46  Total_Amount_std                        float64
 47  Total_Amount_min                        float64
 48  Total_Amount_max                        float64
 49  Last_Activity_Day_mean                  float64
 50  Last_Activity_Day_std                   float64
 51  Last_Activity_Day_min                   float64
 52  Last_Activity_Day_max                   float64
 53  Last_Activity_Month_mean                float64
 54  Last_Activity_Month_std                 float64
 55  Last_Activity_Month_min                 float64
 56  Last_Activity_Month_max                 float64
 57  Last_Activity_Year_mean                 float64
 58  Last_Activity_Year_std                  float64
 59  Last_Activity_Year_min                  float64
 60  Last_Activity_Year_max                  float64
 61  Quote_Expiry_Date_Day_mean              float64
 62  Quote_Expiry_Date_Day_std               float64
 63  Quote_Expiry_Date_Day_min               float64
 64  Quote_Expiry_Date_Day_max               float64
 65  Quote_Expiry_Date_Month_mean            float64
 66  Quote_Expiry_Date_Month_std             float64
 67  Quote_Expiry_Date_Month_min             float64
 68  Quote_Expiry_Date_Month_max             float64
 69  Quote_Expiry_Date_Year_mean             float64
 70  Quote_Expiry_Date_Year_std              float64
 71  Quote_Expiry_Date_Year_min              float64
 72  Quote_Expiry_Date_Year_max              float64
 73  Bit_Product_Family_0_mean               int64
 74  Bit_Product_Family_0_std                float64
 75  Bit_Product_Family_0_min                int64
 76  Bit_Product_Family_0_max                int64
 77  Bit_Product_Family_1_mean               float64
 78  Bit_Product_Family_1_std                float64
 79  Bit_Product_Family_1_min                int64
 80  Bit_Product_Family_1_max                int64
 81  Bit_Product_Family_2_mean               float64
 82  Bit_Product_Family_2_std                float64
 83  Bit_Product_Family_2_min                int64
 84  Bit_Product_Family_2_max                int64
 85  Bit_Product_Family_3_mean               float64
 86  Bit_Product_Family_3_std                float64
 87  Bit_Product_Family_3_min                int64
 88  Bit_Product_Family_3_max                int64
 89  Bit_Product_Family_4_mean               float64
 90  Bit_Product_Family_4_std                float64
 91  Bit_Product_Family_4_min                int64
 92  Bit_Product_Family_4_max                int64
 93  Bit_Product_Family_5_mean               float64
 94  Bit_Product_Family_5_std                float64
 95  Bit_Product_Family_5_min                int64
 96  Bit_Product_Family_5_max                int64
 97  Bit_Product_Family_6_mean               float64
 98  Bit_Product_Family_6_std                float64
 99  Bit_Product_Family_6_min                int64
 100 Bit_Product_Family_6_max                int64
 101 Bit_Product_Family_7_mean               float64
 102 Bit_Product_Family_7_std                float64
 103 Bit_Product_Family_7_min                int64
 104 Bit_Product_Family_7_max                int64
 105 Bit_Product_Family_8_mean               float64
 106 Bit_Product_Family_8_std                float64
 107 Bit_Product_Family_8_min                int64
 108 Bit_Product_Family_8_max                int64
 109 Bit_Product_Name_0_mean                 int64
 110 Bit_Product_Name_0_std                  float64
 111 Bit_Product_Name_0_min                  int64
 112 Bit_Product_Name_0_max                  int64
 113 Bit_Product_Name_1_mean                 float64
 114 Bit_Product_Name_1_std                  float64
 115 Bit_Product_Name_1_min                  int64
 116 Bit_Product_Name_1_max                  int64
 117 Bit_Product_Name_2_mean                 float64
 118 Bit_Product_Name_2_std                  float64
 119 Bit_Product_Name_2_min                  int64
 120 Bit_Product_Name_2_max                  int64
 121 Bit_Product_Name_3_mean                 float64
 122 Bit_Product_Name_3_std                  float64
 123 Bit_Product_Name_3_min                  int64
 124 Bit_Product_Name_3_max                  int64
 125 Bit_Product_Name_4_mean                 float64
 126 Bit_Product_Name_4_std                  float64
 127 Bit_Product_Name_4_min                  int64
 128 Bit_Product_Name_4_max                  int64
 129 Bit_Product_Name_5_mean                 float64
 130 Bit_Product_Name_5_std                  float64
 131 Bit_Product_Name_5_min                  int64
 132 Bit_Product_Name_5_max                  int64
 133 Bit_Product_Name_6_mean                 float64
 134 Bit_Product_Name_6_std                  float64
 135 Bit_Product_Name_6_min                  int64
 136 Bit_Product_Name_6_max                  int64
 137 Bit_Product_Name_7_mean                 float64
 138 Bit_Product_Name_7_std                  float64
 139 Bit_Product_Name_7_min                  int64
 140 Bit_Product_Name_7_max                  int64
 141 Bit_Product_Name_8_mean                 float64
 142 Bit_Product_Name_8_std                  float64
 143 Bit_Product_Name_8_min                  int64
 144 Bit_Product_Name_8_max                  int64
 145 Bit_Product_Name_9_mean                 float64
 146 Bit_Product_Name_9_std                  float64
 147 Bit_Product_Name_9_min                  int64
 148 Bit_Product_Name_9_max                  int64
 149 ASP_mean                                float64
 150 ASP_std                                 float64
 151 ASP_min                                 float64
 152 ASP_max                                 float64
 153 ASP_Currency                            object
 154 ASP_(converted)_mean                    float64
 155 ASP_(converted)_std                     float64
 156 ASP_(converted)_min                     float64
 157 ASP_(converted)_max                     float64
 158 ASP_(converted)_Currency                object
 159 Delivery_Quarter_mean                   float64
 160 Delivery_Quarter_std                    float64
 161 Delivery_Quarter_min                    float64
 162 Delivery_Quarter_max                    float64
 163 Delivery_Year_mean                      float64
 164 Delivery_Year_std                       float64
 165 Delivery_Year_min                       int64
 166 Delivery_Year_max                       int64
 167 Delivery_Month_mean                     float64
 168 Delivery_Month_std                      float64
 169 Delivery_Month_min                      int8
 170 Delivery_Month_max                      int8
 171 Actual_Delivery_Date_Day_mean           float64
 172 Actual_Delivery_Date_Day_std            float64
 173 Actual_Delivery_Date_Day_min            float64
 174 Actual_Delivery_Date_Day_max            float64
 175 Actual_Delivery_Date_Month_mean         float64
 176 Actual_Delivery_Date_Month_std          float64
 177 Actual_Delivery_Date_Month_min          float64
 178 Actual_Delivery_Date_Month_max          float64
 179 Actual_Delivery_Date_Year_mean          float64
 180 Actual_Delivery_Date_Year_std           float64
 181 Actual_Delivery_Date_Year_min           float64
 182 Actual_Delivery_Date_Year_max           float64
 183 Planned_Delivery_Start_Date_Day_mean    float64
 184 Planned_Delivery_Start_Date_Day_std     float64
 185 Planned_Delivery_Start_Date_Day_min     int64
 186 Planned_Delivery_Start_Date_Day_max     int64
 187 Planned_Delivery_Start_Date_Month_mean  float64
 188 Planned_Delivery_Start_Date_Month_std   float64
 189 Planned_Delivery_Start_Date_Month_min   int64
 190 Planned_Delivery_Start_Date_Month_max   int64
 191 Planned_Delivery_Start_Date_Year_mean   float64
 192 Planned_Delivery_Start_Date_Year_std    float64
 193 Planned_Delivery_Start_Date_Year_min    int64
 194 Planned_Delivery_Start_Date_Year_max    int64
 195 Planned_Delivery_End_Date_Day_mean      float64
 196 Planned_Delivery_End_Date_Day_std       float64
 197 Planned_Delivery_End_Date_Day_min       float64
 198 Planned_Delivery_End_Date_Day_max       float64
 199 Planned_Delivery_End_Date_Month_mean    float64
 200 Planned_Delivery_End_Date_Month_std     float64
 201 Planned_Delivery_End_Date_Month_min     float64
 202 Planned_Delivery_End_Date_Month_max     float64
 203 Planned_Delivery_End_Date_Year_mean     float64
 204 Planned_Delivery_End_Date_Year_std      float64
 205 Planned_Delivery_End_Date_Year_min      float64
 206 Planned_Delivery_End_Date_Year_max      float64
 207 Items_by_opportunity                    int64
dtypes: float64(113), int64(66), int8(2), object(27)
memory usage: 15.5+ MB

## Codificación todas las variables categoricas

In [166]:
test_agrupado

,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date_Day,Account_Created_Date_Month,...,Planned_Delivery_End_Date_Day_max,Planned_Delivery_End_Date_Month_mean,Planned_Delivery_End_Date_Month_std,Planned_Delivery_End_Date_Month_min,Planned_Delivery_End_Date_Month_max,Planned_Delivery_End_Date_Year_mean,Planned_Delivery_End_Date_Year_std,Planned_Delivery_End_Date_Year_min,Planned_Delivery_End_Date_Year_max,Items_by_opportunity
0,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,20,2,...,31.0,12.0,0.0,12.0,12.0,2019.0,0.0,2019.0,2019.0,2
1,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,22,8,...,31.0,12.0,NaN,12.0,12.0,2019.0,NaN,2019.0,2019.0,1
2,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,22,8,...,31.0,3.0,0.0,3.0,3.0,2019.0,0.0,2019.0,2019.0,8
3,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,4,4,...,28.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,9
4,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,4,4,...,28.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1562,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,21,8,...,30.0,4.0,NaN,4.0,4.0,2019.0,NaN,2019.0,2019.0,1
1563,Middle East,KSA,1,1,0,0,0,Bureaucratic_Code_4,17,10,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1564,Middle East,KSA,1,1,1,1,0,Bureaucratic_Code_4,15,10,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1565,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,28,12,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1566,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,28,12,...,1.0,6.0,NaN,6.0,6.0,2019.0,NaN,2019.0,2019.0,1

In [167]:
train_agrupado

,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date_Day,Account_Created_Date_Month,...,Planned_Delivery_End_Date_Day_max,Planned_Delivery_End_Date_Month_mean,Planned_Delivery_End_Date_Month_std,Planned_Delivery_End_Date_Month_min,Planned_Delivery_End_Date_Month_max,Planned_Delivery_End_Date_Year_mean,Planned_Delivery_End_Date_Year_std,Planned_Delivery_End_Date_Year_min,Planned_Delivery_End_Date_Year_max,Items_by_opportunity
0,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,11.0,NaN,11.0,11.0,2017.0,NaN,2017.0,2017.0,1
1,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,15.0,12.0,NaN,12.0,12.0,2017.0,NaN,2017.0,2017.0,1
2,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,11.0,NaN,11.0,11.0,2017.0,NaN,2017.0,2017.0,1
3,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,6.0,NaN,6.0,6.0,2017.0,NaN,2017.0,2017.0,1
4,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,19,9,...,29.0,12.0,NaN,12.0,12.0,2017.0,NaN,2017.0,2017.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9836,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,24,1,...,28.0,2.0,NaN,2.0,2.0,2017.0,NaN,2017.0,2017.0,1
9837,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,28,10,...,15.0,12.0,NaN,12.0,12.0,2018.0,NaN,2018.0,2018.0,1
9838,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,28,10,...,1.0,4.0,NaN,4.0,4.0,2019.0,NaN,2019.0,2019.0,1
9839,Middle East,UAE (Others),1,1,1,1,0,Bureaucratic_Code_1,3,7,...,31.0,8.0,NaN,8.0,8.0,2018.0,NaN,2018.0,2018.0,1
9840,Middle East,UAE (Others),1,1,1,1,0,Bureaucratic_Code_4,13,10,...,23.0,12.0,NaN,12.0,12.0,2016.0,NaN,2016.0,2016.0,1

In [168]:

total_agrupado = pd.concat([train_agrupado,test_agrupado], axis=0)
total_agrupado

,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date_Day,Account_Created_Date_Month,...,Planned_Delivery_End_Date_Day_max,Planned_Delivery_End_Date_Month_mean,Planned_Delivery_End_Date_Month_std,Planned_Delivery_End_Date_Month_min,Planned_Delivery_End_Date_Month_max,Planned_Delivery_End_Date_Year_mean,Planned_Delivery_End_Date_Year_std,Planned_Delivery_End_Date_Year_min,Planned_Delivery_End_Date_Year_max,Items_by_opportunity
0,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,11.0,NaN,11.0,11.0,2017.0,NaN,2017.0,2017.0,1
1,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,15.0,12.0,NaN,12.0,12.0,2017.0,NaN,2017.0,2017.0,1
2,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,11.0,NaN,11.0,11.0,2017.0,NaN,2017.0,2017.0,1
3,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,6.0,NaN,6.0,6.0,2017.0,NaN,2017.0,2017.0,1
4,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,19,9,...,29.0,12.0,NaN,12.0,12.0,2017.0,NaN,2017.0,2017.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1562,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,21,8,...,30.0,4.0,NaN,4.0,4.0,2019.0,NaN,2019.0,2019.0,1
1563,Middle East,KSA,1,1,0,0,0,Bureaucratic_Code_4,17,10,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1564,Middle East,KSA,1,1,1,1,0,Bureaucratic_Code_4,15,10,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1565,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,28,12,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1566,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,28,12,...,1.0,6.0,NaN,6.0,6.0,2019.0,NaN,2019.0,2019.0,1

In [169]:
import category_encoders as ce
encoder_Region=ce.BinaryEncoder(cols=['Region'])
total_agrupado_bin1=encoder_Region.fit_transform(total_agrupado['Region'])
total_agrupado_bin1=total_agrupado_bin1.add_prefix('Bit_')

encoder_Territory=ce.BinaryEncoder(cols=['Territory'])
total_agrupado_bin2=encoder_Territory.fit_transform(total_agrupado['Territory'])
total_agrupado_bin2=total_agrupado_bin2.add_prefix('Bit_')

encoder_Bureaucratic_Code=ce.BinaryEncoder(cols=['Bureaucratic_Code'])
total_agrupado_bin3=encoder_Bureaucratic_Code.fit_transform(total_agrupado['Bureaucratic_Code'])
total_agrupado_bin3=total_agrupado_bin3.add_prefix('Bit_')

encoder_Source=ce.BinaryEncoder(cols=['Source '])
total_agrupado_bin4=encoder_Source.fit_transform(total_agrupado['Source '])
total_agrupado_bin4=total_agrupado_bin4.add_prefix('Bit_')

encoder_Billing_Country=ce.BinaryEncoder(cols=['Billing_Country'])
total_agrupado_bin5=encoder_Billing_Country.fit_transform(total_agrupado['Billing_Country'])
total_agrupado_bin5=total_agrupado_bin5.add_prefix('Bit_')



encoder_Account_Name=ce.BinaryEncoder(cols=['Account_Name'])
total_agrupado_bin6=encoder_Account_Name.fit_transform(total_agrupado['Account_Name'])
total_agrupado_bin6=total_agrupado_bin6.add_prefix('Bit_')

encoder_Opportunity_Name=ce.BinaryEncoder(cols=['Opportunity_Name'])
total_agrupado_bin7=encoder_Opportunity_Name.fit_transform(total_agrupado['Opportunity_Name'])
total_agrupado_bin7=total_agrupado_bin7.add_prefix('Bit_')

encoder_Account_Owner=ce.BinaryEncoder(cols=['Account_Owner'])
total_agrupado_bin8=encoder_Account_Owner.fit_transform(total_agrupado['Account_Owner'])
total_agrupado_bin8=total_agrupado_bin8.add_prefix('Bit_')

encoder_Opportunity_Owner=ce.BinaryEncoder(cols=['Opportunity_Owner'])
total_agrupado_bin9=encoder_Opportunity_Owner.fit_transform(total_agrupado['Opportunity_Owner'])
total_agrupado_bin9=total_agrupado_bin9.add_prefix('Bit_')



encoder_Account_Type=ce.BinaryEncoder(cols=['Account_Type'])
total_agrupado_bin10=encoder_Account_Type.fit_transform(total_agrupado['Account_Type'])
total_agrupado_bin10=total_agrupado_bin10.add_prefix('Bit_')


encoder_Opportunity_Type=ce.BinaryEncoder(cols=['Opportunity_Type'])
total_agrupado_bin11=encoder_Opportunity_Type.fit_transform(total_agrupado['Opportunity_Type'])
total_agrupado_bin11=total_agrupado_bin11.add_prefix('Bit_')

encoder_Quote_Type=ce.BinaryEncoder(cols=['Quote_Type'])
total_agrupado_bin12=encoder_Quote_Type.fit_transform(total_agrupado['Quote_Type'])
total_agrupado_bin12=total_agrupado_bin12.add_prefix('Bit_')


encoder_Delivery_Terms=ce.BinaryEncoder(cols=['Delivery_Terms'])
total_agrupado_bin13=encoder_Delivery_Terms.fit_transform(total_agrupado['Delivery_Terms'])
total_agrupado_bin13=total_agrupado_bin13.add_prefix('Bit_')


encoder_Brand=ce.BinaryEncoder(cols=['Brand'])
total_agrupado_bin14=encoder_Brand.fit_transform(total_agrupado['Brand'])
total_agrupado_bin14=total_agrupado_bin14.add_prefix('Bit_')


encoder_Product_Type=ce.BinaryEncoder(cols=['Product_Type'])
total_agrupado_bin15=encoder_Product_Type.fit_transform(total_agrupado['Product_Type'])
total_agrupado_bin15=total_agrupado_bin15.add_prefix('Bit_')


encoder_Size=ce.BinaryEncoder(cols=['Size'])
total_agrupado_bin16=encoder_Size.fit_transform(total_agrupado['Size'])
total_agrupado_bin16=total_agrupado_bin16.add_prefix('Bit_')


encoder_Product_Category_B=ce.BinaryEncoder(cols=['Product_Category_B'])
total_agrupado_bin17=encoder_Product_Category_B.fit_transform(total_agrupado['Product_Category_B'])
total_agrupado_bin17=total_agrupado_bin17.add_prefix('Bit_')


encoder_Currency=ce.BinaryEncoder(cols=['Currency'])
total_agrupado_bin18=encoder_Currency.fit_transform(total_agrupado['Currency'])
total_agrupado_bin18=total_agrupado_bin18.add_prefix('Bit_')

encoder_Last_Modified_By=ce.BinaryEncoder(cols=['Last_Modified_By'])
total_agrupado_bin19=encoder_Last_Modified_By.fit_transform(total_agrupado['Last_Modified_By'])
total_agrupado_bin19=total_agrupado_bin19.add_prefix('Bit_')

encoder_Total_Amount_Currency=ce.BinaryEncoder(cols=['Total_Amount_Currency'])
total_agrupado_bin20=encoder_Total_Amount_Currency.fit_transform(total_agrupado['Total_Amount_Currency'])
total_agrupado_bin20=total_agrupado_bin20.add_prefix('Bit_')


encoder_Total_Taxable_Amount_Currency=ce.BinaryEncoder(cols=['Total_Taxable_Amount_Currency'])
total_agrupado_bin21=encoder_Total_Taxable_Amount_Currency.fit_transform(total_agrupado['Total_Taxable_Amount_Currency'])
total_agrupado_bin21=total_agrupado_bin21.add_prefix('Bit_')

encoder_Prod_Category_A=ce.BinaryEncoder(cols=['Prod_Category_A'])
total_agrupado_bin22=encoder_Prod_Category_A.fit_transform(total_agrupado['Prod_Category_A'])
total_agrupado_bin22=total_agrupado_bin22.add_prefix('Bit_')

encoder_ASP_Currency=ce.BinaryEncoder(cols=['ASP_Currency'])
total_agrupado_bin23=encoder_ASP_Currency.fit_transform(total_agrupado['ASP_Currency'])
total_agrupado_bin23=total_agrupado_bin23.add_prefix('Bit_')

encoder_24=ce.BinaryEncoder(cols=['ASP_(converted)_Currency'])
total_agrupado_bin24=encoder_24.fit_transform(total_agrupado['ASP_(converted)_Currency'])
total_agrupado_bin24=total_agrupado_bin24.add_prefix('Bit_')


total_agrupado_encodeado=pd.concat([total_agrupado,total_agrupado_bin1,total_agrupado_bin2,total_agrupado_bin3,total_agrupado_bin4,total_agrupado_bin5,total_agrupado_bin6,total_agrupado_bin7,total_agrupado_bin8,total_agrupado_bin9,total_agrupado_bin10,total_agrupado_bin11,total_agrupado_bin12,total_agrupado_bin13,total_agrupado_bin14,total_agrupado_bin15,total_agrupado_bin16,total_agrupado_bin17,total_agrupado_bin18,total_agrupado_bin19,total_agrupado_bin20,total_agrupado_bin21,total_agrupado_bin22,total_agrupado_bin23,total_agrupado_bin24],axis=1)
total_agrupado_encodeado = total_agrupado_encodeado.drop(['Region','Territory','Bureaucratic_Code','Source ','Billing_Country','Account_Name','Opportunity_Name','Account_Owner','Opportunity_Owner','Account_Type','Opportunity_Type','Quote_Type','Delivery_Terms','Brand','Product_Type','Size','Product_Category_B','Currency','Last_Modified_By','Total_Amount_Currency','Total_Taxable_Amount_Currency','Prod_Category_A','ASP_Currency','ASP_(converted)_Currency'], axis=1)
total_agrupado_encodeado.head()

/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/home/marcelo/my_project_dir/my_project_env/lib/python3.8/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Account_Created_Date_Day,Account_Created_Date_Month,Account_Created_Date_Year,Opportunity_ID,Sales_Contract_No,...,Bit_Total_Taxable_Amount_Currency_0,Bit_Total_Taxable_Amount_Currency_1,Bit_Total_Taxable_Amount_Currency_2,Bit_Total_Taxable_Amount_Currency_3,Bit_Prod_Category_A_0,Bit_ASP_Currency_0,Bit_ASP_Currency_1,Bit_ASP_Currency_2,Bit_ASP_Currency_3,Bit_ASP_(converted)_Currency_0
0,0,0,0,0,0,1,3,2017,960,None,...,0,0,0,1,1,0,0,0,1,1
1,0,0,0,0,0,1,3,2017,959,None,...,0,0,0,1,1,0,0,0,1,1
2,0,0,0,0,0,1,3,2017,961,None,...,0,0,0,1,1,0,0,0,1,1
3,0,0,0,0,0,1,3,2017,956,None,...,0,0,0,1,1,0,0,0,1,1
4,0,0,0,0,0,19,9,2014,6985,3681,...,0,0,0,1,1,0,0,0,1,1

In [170]:
total_agrupado_encodeado.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11408 entries, 0 to 1566
Data columns (total 315 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   Pricing, Delivery_Terms_Quote_Appr      int64
 1   Pricing, Delivery_Terms_Approved        int64
 2   Bureaucratic_Code_0_Approval            int64
 3   Bureaucratic_Code_0_Approved            int64
 4   Submitted_for_Approval                  int64
 5   Account_Created_Date_Day                int64
 6   Account_Created_Date_Month              int64
 7   Account_Created_Date_Year               int64
 8   Opportunity_ID                          int64
 9   Sales_Contract_No                       object
 10  Opportunity_Created_Date_Day            int64
 11  Opportunity_Created_Date_Month          int64
 12  Opportunity_Created_Date_Year           int64
 13  Price                                   object
 14  Last_Modified_Date_Day                  int64
 15  Last_Modified_Date_Month                int64
 16  Last_Modified_Date_Year                 int64
 17  Total_Taxable_Amount                    float64
 18  Stage                                   object
 19  TRF_mean                                float64
 20  TRF_std                                 float64
 21  TRF_min                                 int64
 22  TRF_max                                 int64
 23  Total_Amount_mean                       float64
 24  Total_Amount_std                        float64
 25  Total_Amount_min                        float64
 26  Total_Amount_max                        float64
 27  Last_Activity_Day_mean                  float64
 28  Last_Activity_Day_std                   float64
 29  Last_Activity_Day_min                   float64
 30  Last_Activity_Day_max                   float64
 31  Last_Activity_Month_mean                float64
 32  Last_Activity_Month_std                 float64
 33  Last_Activity_Month_min                 float64
 34  Last_Activity_Month_max                 float64
 35  Last_Activity_Year_mean                 float64
 36  Last_Activity_Year_std                  float64
 37  Last_Activity_Year_min                  float64
 38  Last_Activity_Year_max                  float64
 39  Quote_Expiry_Date_Day_mean              float64
 40  Quote_Expiry_Date_Day_std               float64
 41  Quote_Expiry_Date_Day_min               float64
 42  Quote_Expiry_Date_Day_max               float64
 43  Quote_Expiry_Date_Month_mean            float64
 44  Quote_Expiry_Date_Month_std             float64
 45  Quote_Expiry_Date_Month_min             float64
 46  Quote_Expiry_Date_Month_max             float64
 47  Quote_Expiry_Date_Year_mean             float64
 48  Quote_Expiry_Date_Year_std              float64
 49  Quote_Expiry_Date_Year_min              float64
 50  Quote_Expiry_Date_Year_max              float64
 51  Bit_Product_Family_0_mean               int64
 52  Bit_Product_Family_0_std                float64
 53  Bit_Product_Family_0_min                int64
 54  Bit_Product_Family_0_max                int64
 55  Bit_Product_Family_1_mean               float64
 56  Bit_Product_Family_1_std                float64
 57  Bit_Product_Family_1_min                int64
 58  Bit_Product_Family_1_max                int64
 59  Bit_Product_Family_2_mean               float64
 60  Bit_Product_Family_2_std                float64
 61  Bit_Product_Family_2_min                int64
 62  Bit_Product_Family_2_max                int64
 63  Bit_Product_Family_3_mean               float64
 64  Bit_Product_Family_3_std                float64
 65  Bit_Product_Family_3_min                int64
 66  Bit_Product_Family_3_max                int64
 67  Bit_Product_Family_4_mean               float64
 68  Bit_Product_Family_4_std                float64
 69  Bit_Product_Family_4_min                int64
 70  Bit_Product_Family_4_max                int64
 71  Bit_Product_Family_5_mean               float64
 72  Bit_Product_Family_5_std                float64
 73  Bit_Product_Family_5_min                int64
 74  Bit_Product_Family_5_max                int64
 75  Bit_Product_Family_6_mean               float64
 76  Bit_Product_Family_6_std                float64
 77  Bit_Product_Family_6_min                int64
 78  Bit_Product_Family_6_max                int64
 79  Bit_Product_Family_7_mean               float64
 80  Bit_Product_Family_7_std                float64
 81  Bit_Product_Family_7_min                int64
 82  Bit_Product_Family_7_max                int64
 83  Bit_Product_Family_8_mean               float64
 84  Bit_Product_Family_8_std                float64
 85  Bit_Product_Family_8_min                int64
 86  Bit_Product_Family_8_max                int64
 87  Bit_Product_Name_0_mean                 int64
 88  Bit_Product_Name_0_std                  float64
 89  Bit_Product_Name_0_min                  int64
 90  Bit_Product_Name_0_max                  int64
 91  Bit_Product_Name_1_mean                 float64
 92  Bit_Product_Name_1_std                  float64
 93  Bit_Product_Name_1_min                  int64
 94  Bit_Product_Name_1_max                  int64
 95  Bit_Product_Name_2_mean                 float64
 96  Bit_Product_Name_2_std                  float64
 97  Bit_Product_Name_2_min                  int64
 98  Bit_Product_Name_2_max                  int64
 99  Bit_Product_Name_3_mean                 float64
 100 Bit_Product_Name_3_std                  float64
 101 Bit_Product_Name_3_min                  int64
 102 Bit_Product_Name_3_max                  int64
 103 Bit_Product_Name_4_mean                 float64
 104 Bit_Product_Name_4_std                  float64
 105 Bit_Product_Name_4_min                  int64
 106 Bit_Product_Name_4_max                  int64
 107 Bit_Product_Name_5_mean                 float64
 108 Bit_Product_Name_5_std                  float64
 109 Bit_Product_Name_5_min                  int64
 110 Bit_Product_Name_5_max                  int64
 111 Bit_Product_Name_6_mean                 float64
 112 Bit_Product_Name_6_std                  float64
 113 Bit_Product_Name_6_min                  int64
 114 Bit_Product_Name_6_max                  int64
 115 Bit_Product_Name_7_mean                 float64
 116 Bit_Product_Name_7_std                  float64
 117 Bit_Product_Name_7_min                  int64
 118 Bit_Product_Name_7_max                  int64
 119 Bit_Product_Name_8_mean                 float64
 120 Bit_Product_Name_8_std                  float64
 121 Bit_Product_Name_8_min                  int64
 122 Bit_Product_Name_8_max                  int64
 123 Bit_Product_Name_9_mean                 float64
 124 Bit_Product_Name_9_std                  float64
 125 Bit_Product_Name_9_min                  int64
 126 Bit_Product_Name_9_max                  int64
 127 ASP_mean                                float64
 128 ASP_std                                 float64
 129 ASP_min                                 float64
 130 ASP_max                                 float64
 131 ASP_(converted)_mean                    float64
 132 ASP_(converted)_std                     float64
 133 ASP_(converted)_min                     float64
 134 ASP_(converted)_max                     float64
 135 Delivery_Quarter_mean                   float64
 136 Delivery_Quarter_std                    float64
 137 Delivery_Quarter_min                    float64
 138 Delivery_Quarter_max                    float64
 139 Delivery_Year_mean                      float64
 140 Delivery_Year_std                       float64
 141 Delivery_Year_min                       int64
 142 Delivery_Year_max                       int64
 143 Delivery_Month_mean                     float64
 144 Delivery_Month_std                      float64
 145 Delivery_Month_min                      int8
 146 Delivery_Month_max                      int8
 147 Actual_Delivery_Date_Day_mean           float64
 148 Actual_Delivery_Date_Day_std            float64
 149 Actual_Delivery_Date_Day_min            float64
 150 Actual_Delivery_Date_Day_max            float64
 151 Actual_Delivery_Date_Month_mean         float64
 152 Actual_Delivery_Date_Month_std          float64
 153 Actual_Delivery_Date_Month_min          float64
 154 Actual_Delivery_Date_Month_max          float64
 155 Actual_Delivery_Date_Year_mean          float64
 156 Actual_Delivery_Date_Year_std           float64
 157 Actual_Delivery_Date_Year_min           float64
 158 Actual_Delivery_Date_Year_max           float64
 159 Planned_Delivery_Start_Date_Day_mean    float64
 160 Planned_Delivery_Start_Date_Day_std     float64
 161 Planned_Delivery_Start_Date_Day_min     int64
 162 Planned_Delivery_Start_Date_Day_max     int64
 163 Planned_Delivery_Start_Date_Month_mean  float64
 164 Planned_Delivery_Start_Date_Month_std   float64
 165 Planned_Delivery_Start_Date_Month_min   int64
 166 Planned_Delivery_Start_Date_Month_max   int64
 167 Planned_Delivery_Start_Date_Year_mean   float64
 168 Planned_Delivery_Start_Date_Year_std    float64
 169 Planned_Delivery_Start_Date_Year_min    int64
 170 Planned_Delivery_Start_Date_Year_max    int64
 171 Planned_Delivery_End_Date_Day_mean      float64
 172 Planned_Delivery_End_Date_Day_std       float64
 173 Planned_Delivery_End_Date_Day_min       float64
 174 Planned_Delivery_End_Date_Day_max       float64
 175 Planned_Delivery_End_Date_Month_mean    float64
 176 Planned_Delivery_End_Date_Month_std     float64
 177 Planned_Delivery_End_Date_Month_min     float64
 178 Planned_Delivery_End_Date_Month_max     float64
 179 Planned_Delivery_End_Date_Year_mean     float64
 180 Planned_Delivery_End_Date_Year_std      float64
 181 Planned_Delivery_End_Date_Year_min      float64
 182 Planned_Delivery_End_Date_Year_max      float64
 183 Items_by_opportunity                    int64
 184 Bit_Region_0                            int64
 185 Bit_Region_1                            int64
 186 Bit_Region_2                            int64
 187 Bit_Region_3                            int64
 188 Bit_Territory_0                         int64
 189 Bit_Territory_1                         int64
 190 Bit_Territory_2                         int64
 191 Bit_Territory_3                         int64
 192 Bit_Territory_4                         int64
 193 Bit_Territory_5                         int64
 194 Bit_Territory_6                         int64
 195 Bit_Territory_7                         int64
 196 Bit_Bureaucratic_Code_0                 int64
 197 Bit_Bureaucratic_Code_1                 int64
 198 Bit_Bureaucratic_Code_2                 int64
 199 Bit_Bureaucratic_Code_3                 int64
 200 Bit_Source _0                           int64
 201 Bit_Source _1                           int64
 202 Bit_Source _2                           int64
 203 Bit_Source _3                           int64
 204 Bit_Source _4                           int64
 205 Bit_Billing_Country_0                   int64
 206 Bit_Billing_Country_1                   int64
 207 Bit_Billing_Country_2                   int64
 208 Bit_Billing_Country_3                   int64
 209 Bit_Billing_Country_4                   int64
 210 Bit_Billing_Country_5                   int64
 211 Bit_Billing_Country_6                   int64
 212 Bit_Billing_Country_7                   int64
 213 Bit_Account_Name_0                      int64
 214 Bit_Account_Name_1                      int64
 215 Bit_Account_Name_2                      int64
 216 Bit_Account_Name_3                      int64
 217 Bit_Account_Name_4                      int64
 218 Bit_Account_Name_5                      int64
 219 Bit_Account_Name_6                      int64
 220 Bit_Account_Name_7                      int64
 221 Bit_Account_Name_8                      int64
 222 Bit_Account_Name_9                      int64
 223 Bit_Account_Name_10                     int64
 224 Bit_Account_Name_11                     int64
 225 Bit_Opportunity_Name_0                  int64
 226 Bit_Opportunity_Name_1                  int64
 227 Bit_Opportunity_Name_2                  int64
 228 Bit_Opportunity_Name_3                  int64
 229 Bit_Opportunity_Name_4                  int64
 230 Bit_Opportunity_Name_5                  int64
 231 Bit_Opportunity_Name_6                  int64
 232 Bit_Opportunity_Name_7                  int64
 233 Bit_Opportunity_Name_8                  int64
 234 Bit_Opportunity_Name_9                  int64
 235 Bit_Opportunity_Name_10                 int64
 236 Bit_Opportunity_Name_11                 int64
 237 Bit_Opportunity_Name_12                 int64
 238 Bit_Opportunity_Name_13                 int64
 239 Bit_Opportunity_Name_14                 int64
 240 Bit_Account_Owner_0                     int64
 241 Bit_Account_Owner_1                     int64
 242 Bit_Account_Owner_2                     int64
 243 Bit_Account_Owner_3                     int64
 244 Bit_Account_Owner_4                     int64
 245 Bit_Account_Owner_5                     int64
 246 Bit_Account_Owner_6                     int64
 247 Bit_Opportunity_Owner_0                 int64
 248 Bit_Opportunity_Owner_1                 int64
 249 Bit_Opportunity_Owner_2                 int64
 250 Bit_Opportunity_Owner_3                 int64
 251 Bit_Opportunity_Owner_4                 int64
 252 Bit_Opportunity_Owner_5                 int64
 253 Bit_Opportunity_Owner_6                 int64
 254 Bit_Account_Type_0                      int64
 255 Bit_Account_Type_1                      int64
 256 Bit_Account_Type_2                      int64
 257 Bit_Account_Type_3                      int64
 258 Bit_Opportunity_Type_0                  int64
 259 Bit_Opportunity_Type_1                  int64
 260 Bit_Opportunity_Type_2                  int64
 261 Bit_Opportunity_Type_3                  int64
 262 Bit_Opportunity_Type_4                  int64
 263 Bit_Opportunity_Type_5                  int64
 264 Bit_Quote_Type_0                        int64
 265 Bit_Quote_Type_1                        int64
 266 Bit_Delivery_Terms_0                    int64
 267 Bit_Delivery_Terms_1                    int64
 268 Bit_Delivery_Terms_2                    int64
 269 Bit_Delivery_Terms_3                    int64
 270 Bit_Delivery_Terms_4                    int64
 271 Bit_Brand_0                             int64
 272 Bit_Brand_1                             int64
 273 Bit_Brand_2                             int64
 274 Bit_Brand_3                             int64
 275 Bit_Brand_4                             int64
 276 Bit_Brand_5                             int64
 277 Bit_Product_Type_0                      int64
 278 Bit_Product_Type_1                      int64
 279 Bit_Product_Type_2                      int64
 280 Bit_Product_Type_3                      int64
 281 Bit_Size_0                              int64
 282 Bit_Size_1                              int64
 283 Bit_Size_2                              int64
 284 Bit_Size_3                              int64
 285 Bit_Product_Category_B_0                int64
 286 Bit_Product_Category_B_1                int64
 287 Bit_Product_Category_B_2                int64
 288 Bit_Product_Category_B_3                int64
 289 Bit_Product_Category_B_4                int64
 290 Bit_Product_Category_B_5                int64
 291 Bit_Currency_0                          int64
 292 Bit_Currency_1                          int64
 293 Bit_Currency_2                          int64
 294 Bit_Last_Modified_By_0                  int64
 295 Bit_Last_Modified_By_1                  int64
 296 Bit_Last_Modified_By_2                  int64
 297 Bit_Last_Modified_By_3                  int64
 298 Bit_Last_Modified_By_4                  int64
 299 Bit_Last_Modified_By_5                  int64
 300 Bit_Last_Modified_By_6                  int64
 301 Bit_Total_Amount_Currency_0             int64
 302 Bit_Total_Amount_Currency_1             int64
 303 Bit_Total_Amount_Currency_2             int64
 304 Bit_Total_Amount_Currency_3             int64
 305 Bit_Total_Taxable_Amount_Currency_0     int64
 306 Bit_Total_Taxable_Amount_Currency_1     int64
 307 Bit_Total_Taxable_Amount_Currency_2     int64
 308 Bit_Total_Taxable_Amount_Currency_3     int64
 309 Bit_Prod_Category_A_0                   int64
 310 Bit_ASP_Currency_0                      int64
 311 Bit_ASP_Currency_1                      int64
 312 Bit_ASP_Currency_2                      int64
 313 Bit_ASP_Currency_3                      int64
 314 Bit_ASP_(converted)_Currency_0          int64
dtypes: float64(113), int64(197), int8(2), object(3)
memory usage: 27.4+ MB

In [171]:
train_agrupado_encodeado = total_agrupado_encodeado.iloc[:9841,:] 
test_agrupado_encodeado = total_agrupado_encodeado.iloc[9841:,:]

In [193]:
train_agrupado_encodeado

,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Account_Created_Date_Day,Account_Created_Date_Month,Account_Created_Date_Year,Opportunity_ID,Sales_Contract_No,...,Bit_Total_Taxable_Amount_Currency_0,Bit_Total_Taxable_Amount_Currency_1,Bit_Total_Taxable_Amount_Currency_2,Bit_Total_Taxable_Amount_Currency_3,Bit_Prod_Category_A_0,Bit_ASP_Currency_0,Bit_ASP_Currency_1,Bit_ASP_Currency_2,Bit_ASP_Currency_3,Bit_ASP_(converted)_Currency_0
0,0,0,0,0,0,1,3,2017,960,0,...,0,0,0,1,1,0,0,0,1,1
1,0,0,0,0,0,1,3,2017,959,0,...,0,0,0,1,1,0,0,0,1,1
2,0,0,0,0,0,1,3,2017,961,0,...,0,0,0,1,1,0,0,0,1,1
3,0,0,0,0,0,1,3,2017,956,0,...,0,0,0,1,1,0,0,0,1,1
4,0,0,0,0,0,19,9,2014,6985,3681,...,0,0,0,1,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9836,1,1,1,1,0,24,1,2017,535,0,...,0,0,0,1,1,0,0,0,1,1
9837,1,1,1,1,0,28,10,2018,9968,0,...,0,0,0,1,1,0,0,0,1,1
9838,1,1,1,1,0,28,10,2018,10157,0,...,0,0,0,1,1,0,0,0,1,1
9839,1,1,1,1,0,3,7,2018,8740,4645,...,0,0,0,1,1,0,0,0,1,1
9840,1,1,1,1,0,13,10,2016,3257,1080,...,0,0,0,1,1,0,0,0,1,1

In [194]:
test_agrupado_encodeado

,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Account_Created_Date_Day,Account_Created_Date_Month,Account_Created_Date_Year,Opportunity_ID,Sales_Contract_No,...,Bit_Total_Taxable_Amount_Currency_0,Bit_Total_Taxable_Amount_Currency_1,Bit_Total_Taxable_Amount_Currency_2,Bit_Total_Taxable_Amount_Currency_3,Bit_Prod_Category_A_0,Bit_ASP_Currency_0,Bit_ASP_Currency_1,Bit_ASP_Currency_2,Bit_ASP_Currency_3,Bit_ASP_(converted)_Currency_0
0,0,0,0,0,0,20,2,2017,12173,0,...,0,0,0,1,1,0,0,0,1,1
1,0,0,0,0,0,22,8,2018,12172,0,...,0,0,0,1,1,0,0,0,1,1
2,0,0,0,0,0,22,8,2018,11408,0,...,0,0,0,1,1,0,0,0,1,1
3,0,0,0,0,0,4,4,2019,12232,0,...,0,0,0,1,1,0,0,0,1,1
4,0,0,0,0,0,4,4,2019,12233,0,...,0,0,0,1,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1562,1,1,1,1,0,21,8,2017,11758,0,...,0,0,0,1,1,0,0,0,1,1
1563,1,1,0,0,0,17,10,2018,10721,0,...,0,0,0,1,1,0,0,0,1,1
1564,1,1,1,1,0,15,10,2018,11757,0,...,0,0,0,1,1,0,0,0,1,1
1565,1,1,1,1,0,28,12,2017,10851,0,...,0,0,0,1,1,0,0,0,1,1
1566,1,1,1,1,0,28,12,2017,10880,0,...,0,0,0,1,1,0,0,0,1,1

In [196]:
test_agrupado_encodeado.replace(to_replace='None', value=np.nan, inplace=True)

In [197]:
test_agrupado_encodeado.replace(to_replace='Other', value=np.nan, inplace=True)

In [198]:
test_agrupado_encodeado.replace(to_replace=[None], value=np.nan, inplace=True)

In [199]:
test_agrupado_encodeado=test_agrupado_encodeado.fillna(0)

In [190]:
train_agrupado_encodeado.replace(to_replace='None', value=np.nan, inplace=True)

In [ ]:
train_agrupado_encodeado.replace(to_replace='Other', value=np.nan, inplace=True)

In [191]:
train_agrupado_encodeado.replace(to_replace=[None], value=np.nan, inplace=True)

In [192]:
train_agrupado_encodeado=train_agrupado_encodeado.fillna(0)

In [195]:
test_agrupado_encodeado.to_csv(r'./Test_Preprocesado_TP2_Datos_2020-2C-encodeado.csv',index=False , header=True)
train_agrupado_encodeado.to_csv(r'./Train_Preprocesado_TP2_Datos_2020-2C-encodeado.csv',index=False , header=True)